// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project af460206e137e8d8 "Sapient", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Desktop-sm' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-WYLQLMGG.js";
import { routes } from "./chunks/chunk-PZVC6U2W.js";

// virtual:fa-qs
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:/framer-cms/modules/2vJjsMd5sPs1piC9sSv4/U4bW4FughaOfPuzaImWr/Qz_wO8lJ9.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var QuestionFAQFonts = getFonts(stdin_default);
var cycleOrder = ["QoyiWMkdj", "VakuvyNg8", "GyWV9AsFb", "RW5DR0tov"];
var serializationHash = "framer-bAPt0";
var variantClassNames = {
	GyWV9AsFb: "framer-v-sh16l",
	QoyiWMkdj: "framer-v-krsan6",
	RW5DR0tov: "framer-v-1k04bgg",
	VakuvyNg8: "framer-v-3m9p23",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Desktop-sm": "VakuvyNg8",
	Desktop: "QoyiWMkdj",
	Phone: "RW5DR0tov",
	Tablet: "GyWV9AsFb",
};
var getProps = ({ height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "QoyiWMkdj",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "QoyiWMkdj",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "RW5DR0tov") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "VakuvyNg8") return false;
		return true;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "VakuvyNg8") return true;
		return false;
	};
	const isDisplayed3 = () => {
		if (baseVariant === "RW5DR0tov") return true;
		return false;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-krsan6",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"QoyiWMkdj"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								GyWV9AsFb: {
									"data-framer-name": "Tablet",
								},
								RW5DR0tov: {
									"data-framer-name": "Phone",
								},
								VakuvyNg8: {
									"data-framer-name": "Desktop-sm",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<RichText
								__fromCanvasComponent={true}
								className={"framer-oqio6h"}
								data-framer-name={"Frequently Asked Questions"}
								fonts={["GF;Plus Jakarta Sans-700"]}
								layoutDependency={layoutDependency}
								layoutId={"H4vgQBoQn"}
								style={{
									"--extracted-1w3ko1f": "rgba(23, 35, 30, 1)",
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"bottom"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--framer-font-size": "36px",
											"--framer-line-height": "145%",
											"--framer-text-alignment": "center",
										}}
									>
										<motion.span
											style={{
												"--font-selector": "R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
												"--framer-font-family": '"Plus Jakarta Sans"',
												"--framer-font-size": "36px",
												"--framer-font-weight": "700",
												"--framer-text-color":
													"var(--extracted-1w3ko1f, rgba(23, 35, 30, 1))",
											}}
										>
											{"Frequently Asked Questions"}
										</motion.span>
									</motion.p>
								</React.Fragment>
							</RichText>
						)}
						{isDisplayed() && (
							<motion.div
								className={"framer-15451u"}
								data-framer-name={"Frame 1000004903"}
								layoutDependency={layoutDependency}
								layoutId={"dQFh8B6TC"}
							>
								{isDisplayed1() && (
									<motion.div
										className={"framer-1nai6gd"}
										data-framer-name={"Frame 1000004831"}
										layoutDependency={layoutDependency}
										layoutId={"Z2OaBzCOJ"}
									>
										<ComponentViewportProvider
											height={72}
											width={"580px"}
											y={
												((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.y) || 0) +
												100 +
												301 +
												0 +
												0 +
												0
											}
											{...addPropertyOverrides(
												{
													GyWV9AsFb: {
														y:
															((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.y) || 0) +
															40 +
															301 +
															0 +
															0 +
															0 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<motion.div
												className={"framer-1h7ebed-container"}
												layoutDependency={layoutDependency}
												layoutId={"JeJiTXxRk-container"}
											>
												{_jsx(stdin_default, {
													fDOQewoVL:
														"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
													height: "100%",
													id: "JeJiTXxRk",
													layoutId: "JeJiTXxRk",
													nAIvabsq8:
														"We offer a comprehensive range of financial services, including wealth management, loan planning, retirement planning, tax planning, investment advice, insurance services, and education savings plans. Our goal is to help you achieve financial security and grow your wealth.",
													style: {
														width: "100%",
													},
													variant: "pSNBCEMlG",
													width: "100%",
													wX23zzvm6: "About the product goes here!",
													wzShjY0g9: "What services does your company provide?",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={72}
											width={"580px"}
											y={
												((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.y) || 0) +
												100 +
												301 +
												0 +
												0 +
												96
											}
											{...addPropertyOverrides(
												{
													GyWV9AsFb: {
														y:
															((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.y) || 0) +
															40 +
															301 +
															0 +
															0 +
															0 +
															88,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<motion.div
												className={"framer-1xutir2-container"}
												layoutDependency={layoutDependency}
												layoutId={"zRw1ivv_P-container"}
											>
												{_jsx(stdin_default, {
													fDOQewoVL:
														"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
													height: "100%",
													id: "zRw1ivv_P",
													layoutId: "zRw1ivv_P",
													nAIvabsq8:
														"You can get started by booking a free consultation through our website. During the consultation, we'll assess your financial needs and provide tailored advice to help you achieve your goals.",
													style: {
														width: "100%",
													},
													variant: "qKj0t2Szi",
													width: "100%",
													wX23zzvm6: "About the product goes here!",
													wzShjY0g9: "How do I get started with your services?",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={72}
											width={"580px"}
											y={
												((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.y) || 0) +
												100 +
												301 +
												0 +
												0 +
												192
											}
											{...addPropertyOverrides(
												{
													GyWV9AsFb: {
														y:
															((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.y) || 0) +
															40 +
															301 +
															0 +
															0 +
															0 +
															176,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<motion.div
												className={"framer-18ap0fr-container"}
												layoutDependency={layoutDependency}
												layoutId={"bKGj0z5fp-container"}
											>
												{_jsx(stdin_default, {
													fDOQewoVL:
														"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
													height: "100%",
													id: "bKGj0z5fp",
													layoutId: "bKGj0z5fp",
													nAIvabsq8:
														"We serve a diverse range of clients including individuals, families, business owners, NRIs (Non-Resident Indians), and high-net-worth individuals. We customize our services to meet the specific needs of each client segment.",
													style: {
														width: "100%",
													},
													variant: "qKj0t2Szi",
													width: "100%",
													wX23zzvm6: "About the product goes here!",
													wzShjY0g9: "Who are your typical clients?",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={72}
											width={"580px"}
											y={
												((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.y) || 0) +
												100 +
												301 +
												0 +
												0 +
												288
											}
											{...addPropertyOverrides(
												{
													GyWV9AsFb: {
														y:
															((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.y) || 0) +
															40 +
															301 +
															0 +
															0 +
															0 +
															264,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<motion.div
												className={"framer-biedbl-container"}
												layoutDependency={layoutDependency}
												layoutId={"t7nhNvA7x-container"}
											>
												{_jsx(stdin_default, {
													fDOQewoVL:
														"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
													height: "100%",
													id: "t7nhNvA7x",
													layoutId: "t7nhNvA7x",
													nAIvabsq8:
														"Our approach is centered on our S.T.E.A.R commitment\u2014Service, Trust, Empathy, Advice, and Relationship. We prioritize building long-term relationships with our clients, offering personalized advice, and maintaining a deep understanding of your financial needs.",
													style: {
														width: "100%",
													},
													variant: "qKj0t2Szi",
													width: "100%",
													wX23zzvm6: "About the product goes here!",
													wzShjY0g9: "What makes your services unique?",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={72}
											width={"580px"}
											y={
												((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.y) || 0) +
												100 +
												301 +
												0 +
												0 +
												384
											}
											{...addPropertyOverrides(
												{
													GyWV9AsFb: {
														y:
															((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.y) || 0) +
															40 +
															301 +
															0 +
															0 +
															0 +
															352,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<motion.div
												className={"framer-1ynuxch-container"}
												layoutDependency={layoutDependency}
												layoutId={"tcYCV8XeO-container"}
											>
												{_jsx(stdin_default, {
													fDOQewoVL:
														"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
													height: "100%",
													id: "tcYCV8XeO",
													layoutId: "tcYCV8XeO",
													nAIvabsq8:
														"Yes, we have a global presence with expertise in handling KYC (Know Your Customer) regulations, taxation, and investment strategies for clients worldwide.",
													style: {
														width: "100%",
													},
													variant: "qKj0t2Szi",
													width: "100%",
													wX23zzvm6: "About the product goes here!",
													wzShjY0g9: "Are your services available globally?",
												})}
											</motion.div>
										</ComponentViewportProvider>
									</motion.div>
								)}
								<motion.div
									className={"framer-1uk2tvx"}
									data-framer-name={"Frame 1000004832"}
									layoutDependency={layoutDependency}
									layoutId={"QBYBUAaIW"}
								>
									<ComponentViewportProvider
										height={72}
										width={"580px"}
										y={
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											100 +
											301 +
											0 +
											0 +
											0
										}
										{...addPropertyOverrides(
											{
												GyWV9AsFb: {
													y:
														((componentViewport === null ||
														componentViewport === void 0
															? void 0
															: componentViewport.y) || 0) +
														40 +
														301 +
														0 +
														440 +
														0 +
														0,
												},
												VakuvyNg8: {
													width: `max((${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} - 72px) / 2, 1px)`,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<motion.div
											className={"framer-1ipz5yv-container"}
											layoutDependency={layoutDependency}
											layoutId={"Zn9v8T6DZ-container"}
										>
											{_jsx(stdin_default, {
												fDOQewoVL:
													"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
												height: "100%",
												id: "Zn9v8T6DZ",
												layoutId: "Zn9v8T6DZ",
												nAIvabsq8:
													"We implement robust security measures to protect your personal and financial information. Our team adheres to strict confidentiality protocols, and our systems are designed to safeguard your data against unauthorized access.",
												style: {
													width: "100%",
												},
												variant: "qKj0t2Szi",
												width: "100%",
												wX23zzvm6: "About the product goes here!",
												wzShjY0g9:
													"How to ensure my financial information's security?",
											})}
										</motion.div>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={72}
										width={"580px"}
										y={
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											100 +
											301 +
											0 +
											0 +
											96
										}
										{...addPropertyOverrides(
											{
												GyWV9AsFb: {
													y:
														((componentViewport === null ||
														componentViewport === void 0
															? void 0
															: componentViewport.y) || 0) +
														40 +
														301 +
														0 +
														440 +
														0 +
														88,
												},
												VakuvyNg8: {
													width: `max((${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} - 72px) / 2, 1px)`,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<motion.div
											className={"framer-fqz9pu-container"}
											layoutDependency={layoutDependency}
											layoutId={"ZGgfQgg9l-container"}
										>
											{_jsx(stdin_default, {
												fDOQewoVL:
													"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
												height: "100%",
												id: "ZGgfQgg9l",
												layoutId: "ZGgfQgg9l",
												nAIvabsq8:
													"Our fee structure is transparent and tailored to the services you require. We offer both fixed-fee and percentage-based models, depending on the type of service and the complexity of your financial plan.",
												style: {
													width: "100%",
												},
												variant: "qKj0t2Szi",
												width: "100%",
												wX23zzvm6: "About the product goes here!",
												wzShjY0g9: "What is your fee structure?",
											})}
										</motion.div>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={72}
										width={"580px"}
										y={
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											100 +
											301 +
											0 +
											0 +
											192
										}
										{...addPropertyOverrides(
											{
												GyWV9AsFb: {
													y:
														((componentViewport === null ||
														componentViewport === void 0
															? void 0
															: componentViewport.y) || 0) +
														40 +
														301 +
														0 +
														440 +
														0 +
														176,
												},
												VakuvyNg8: {
													width: `max((${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} - 72px) / 2, 1px)`,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<motion.div
											className={"framer-hkae7t-container"}
											layoutDependency={layoutDependency}
											layoutId={"qRk88vUv6-container"}
										>
											{_jsx(stdin_default, {
												fDOQewoVL:
													"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
												height: "100%",
												id: "qRk88vUv6",
												layoutId: "qRk88vUv6",
												nAIvabsq8:
													'Yes, you can easily schedule a consultation through our website. Just click on the "Book a Free Consultation" button, select a convenient time, and fill in your details.',
												style: {
													width: "100%",
												},
												variant: "qKj0t2Szi",
												width: "100%",
												wX23zzvm6: "About the product goes here!",
												wzShjY0g9: "Can I schedule a consultation online?",
											})}
										</motion.div>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={72}
										width={"580px"}
										y={
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											100 +
											301 +
											0 +
											0 +
											288
										}
										{...addPropertyOverrides(
											{
												GyWV9AsFb: {
													y:
														((componentViewport === null ||
														componentViewport === void 0
															? void 0
															: componentViewport.y) || 0) +
														40 +
														301 +
														0 +
														440 +
														0 +
														264,
												},
												VakuvyNg8: {
													width: `max((${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} - 72px) / 2, 1px)`,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<motion.div
											className={"framer-1d8f3kc-container"}
											layoutDependency={layoutDependency}
											layoutId={"XqrNe47OZ-container"}
										>
											{_jsx(stdin_default, {
												fDOQewoVL:
													"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
												height: "100%",
												id: "XqrNe47OZ",
												layoutId: "XqrNe47OZ",
												nAIvabsq8:
													"You can contact your advisor directly via phone or email. Additionally, you can schedule a meeting through our website or through the client portal.",
												style: {
													width: "100%",
												},
												variant: "qKj0t2Szi",
												width: "100%",
												wX23zzvm6: "About the product goes here!",
												wzShjY0g9: "How can I get in touch with my advisor?",
											})}
										</motion.div>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={72}
										width={"580px"}
										y={
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
											100 +
											301 +
											0 +
											0 +
											384
										}
										{...addPropertyOverrides(
											{
												GyWV9AsFb: {
													y:
														((componentViewport === null ||
														componentViewport === void 0
															? void 0
															: componentViewport.y) || 0) +
														40 +
														301 +
														0 +
														440 +
														0 +
														352,
												},
												VakuvyNg8: {
													width: `max((${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} - 72px) / 2, 1px)`,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<motion.div
											className={"framer-zqrdb1-container"}
											layoutDependency={layoutDependency}
											layoutId={"aB9okRf_B-container"}
										>
											{_jsx(stdin_default, {
												fDOQewoVL:
													"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
												height: "100%",
												id: "aB9okRf_B",
												layoutId: "aB9okRf_B",
												nAIvabsq8:
													"Yes, we specialize in providing financial planning, investment strategies, and tax advisory services tailored to the needs of Non-Resident Indians (NRIs).",
												style: {
													width: "100%",
												},
												variant: "qKj0t2Szi",
												width: "100%",
												wX23zzvm6: "About the product goes here!",
												wzShjY0g9: "Do you offer services for NRIs?",
											})}
										</motion.div>
									</ComponentViewportProvider>
								</motion.div>
								{isDisplayed2() && (
									<motion.div
										className={"framer-1emurrl"}
										data-framer-name={"Frame 1000004832"}
										layoutDependency={layoutDependency}
										layoutId={"irpCh9fnW"}
									>
										<ComponentViewportProvider
											height={72}
											{...addPropertyOverrides(
												{
													VakuvyNg8: {
														width: `max((${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} - 72px) / 2, 1px)`,
														y:
															((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.y) || 0) +
															100 +
															301 +
															0 +
															0 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<motion.div
												className={"framer-acv4hz-container"}
												layoutDependency={layoutDependency}
												layoutId={"rfG07G0kh-container"}
											>
												{_jsx(stdin_default, {
													fDOQewoVL:
														"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
													height: "100%",
													id: "rfG07G0kh",
													layoutId: "rfG07G0kh",
													nAIvabsq8:
														"We offer a comprehensive range of financial services, including wealth management, loan planning, retirement planning, tax planning, investment advice, insurance services, and education savings plans. Our goal is to help you achieve financial security and grow your wealth.",
													style: {
														width: "100%",
													},
													variant: "pSNBCEMlG",
													width: "100%",
													wX23zzvm6: "About the product goes here!",
													wzShjY0g9: "What services does your company provide?",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={72}
											{...addPropertyOverrides(
												{
													VakuvyNg8: {
														width: `max((${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} - 72px) / 2, 1px)`,
														y:
															((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.y) || 0) +
															100 +
															301 +
															0 +
															0 +
															96,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<motion.div
												className={"framer-lsjjrt-container"}
												layoutDependency={layoutDependency}
												layoutId={"bd_5m6m5P-container"}
											>
												{_jsx(stdin_default, {
													fDOQewoVL:
														"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
													height: "100%",
													id: "bd_5m6m5P",
													layoutId: "bd_5m6m5P",
													nAIvabsq8:
														"You can get started by booking a free consultation through our website. During the consultation, we'll assess your financial needs and provide tailored advice to help you achieve your goals.",
													style: {
														width: "100%",
													},
													variant: "qKj0t2Szi",
													width: "100%",
													wX23zzvm6: "About the product goes here!",
													wzShjY0g9: "How do I get started with your services?",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={72}
											{...addPropertyOverrides(
												{
													VakuvyNg8: {
														width: `max((${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} - 72px) / 2, 1px)`,
														y:
															((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.y) || 0) +
															100 +
															301 +
															0 +
															0 +
															192,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<motion.div
												className={"framer-rpwhxs-container"}
												layoutDependency={layoutDependency}
												layoutId={"f1htVeFDv-container"}
											>
												{_jsx(stdin_default, {
													fDOQewoVL:
														"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
													height: "100%",
													id: "f1htVeFDv",
													layoutId: "f1htVeFDv",
													nAIvabsq8:
														"We serve a diverse range of clients including individuals, families, business owners, NRIs (Non-Resident Indians), and high-net-worth individuals. We customize our services to meet the specific needs of each client segment.",
													style: {
														width: "100%",
													},
													variant: "qKj0t2Szi",
													width: "100%",
													wX23zzvm6: "About the product goes here!",
													wzShjY0g9: "Who are your typical clients?",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={72}
											{...addPropertyOverrides(
												{
													VakuvyNg8: {
														width: `max((${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} - 72px) / 2, 1px)`,
														y:
															((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.y) || 0) +
															100 +
															301 +
															0 +
															0 +
															288,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<motion.div
												className={"framer-17cbgfy-container"}
												layoutDependency={layoutDependency}
												layoutId={"j0dplHHAu-container"}
											>
												{_jsx(stdin_default, {
													fDOQewoVL:
														"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
													height: "100%",
													id: "j0dplHHAu",
													layoutId: "j0dplHHAu",
													nAIvabsq8:
														"Our approach is centered on our S.T.E.A.R commitment\u2014Service, Trust, Empathy, Advice, and Relationship. We prioritize building long-term relationships with our clients, offering personalized advice, and maintaining a deep understanding of your financial needs.",
													style: {
														width: "100%",
													},
													variant: "qKj0t2Szi",
													width: "100%",
													wX23zzvm6: "About the product goes here!",
													wzShjY0g9: "What makes your services unique?",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={72}
											{...addPropertyOverrides(
												{
													VakuvyNg8: {
														width: `max((${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} - 72px) / 2, 1px)`,
														y:
															((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.y) || 0) +
															100 +
															301 +
															0 +
															0 +
															384,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<motion.div
												className={"framer-1397qk-container"}
												layoutDependency={layoutDependency}
												layoutId={"pvDtqtHEn-container"}
											>
												{_jsx(stdin_default, {
													fDOQewoVL:
														"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
													height: "100%",
													id: "pvDtqtHEn",
													layoutId: "pvDtqtHEn",
													nAIvabsq8:
														"Yes, we have a global presence with expertise in handling KYC (Know Your Customer) regulations, taxation, and investment strategies for clients worldwide.",
													style: {
														width: "100%",
													},
													variant: "qKj0t2Szi",
													width: "100%",
													wX23zzvm6: "About the product goes here!",
													wzShjY0g9: "Are your services available globally?",
												})}
											</motion.div>
										</ComponentViewportProvider>
									</motion.div>
								)}
							</motion.div>
						)}
						{isDisplayed3() && (
							<motion.div
								className={"framer-19w6g9l"}
								data-framer-name={"Frame 1430105498"}
								layoutDependency={layoutDependency}
								layoutId={"iRHygIxb5"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-17h0jte"}
									data-framer-name={"Frequently Asked Questions"}
									fonts={["GF;Plus Jakarta Sans-700"]}
									layoutDependency={layoutDependency}
									layoutId={"E6ywUSJZd"}
									style={{
										"--extracted-r6o4lv": "rgb(23, 35, 30)",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"bottom"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--font-selector": "R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
												"--framer-font-family":
													'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
												"--framer-font-size": "24px",
												"--framer-font-weight": "700",
												"--framer-letter-spacing": "-0.01em",
												"--framer-line-height": "120%",
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgb(23, 35, 30))",
											}}
										>
											{"Frequently Asked Questions"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<motion.div
									className={"framer-v9u159"}
									data-framer-name={"Frame 1430105668"}
									layoutDependency={layoutDependency}
									layoutId={"BDW47LVpH"}
								>
									<motion.div
										className={"framer-1pgbb5z"}
										data-framer-name={"Frame 1000004831"}
										layoutDependency={layoutDependency}
										layoutId={"V4nYWWELD"}
									>
										<ComponentViewportProvider
											height={72}
											width={"343px"}
											{...addPropertyOverrides(
												{
													RW5DR0tov: {
														y:
															((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.y) || 0) +
															40 +
															0 +
															0 +
															176 +
															0 +
															0 +
															0 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<motion.div
												className={"framer-nff70i-container"}
												layoutDependency={layoutDependency}
												layoutId={"kAENWCA39-container"}
											>
												{_jsx(stdin_default, {
													fDOQewoVL:
														"You can get started by booking a free consultation through our website. During the consultation, we'll assess your financial needs and provide tailored advice to help you achieve your goals.",
													height: "100%",
													id: "kAENWCA39",
													layoutId: "kAENWCA39",
													nAIvabsq8:
														"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
													style: {
														width: "100%",
													},
													variant: "ald8i_pcX",
													width: "100%",
													wX23zzvm6: "How do I get started with your services?",
													wzShjY0g9: "Question 1 about the product goes here!",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={72}
											width={"343px"}
											{...addPropertyOverrides(
												{
													RW5DR0tov: {
														y:
															((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.y) || 0) +
															40 +
															0 +
															0 +
															176 +
															0 +
															0 +
															0 +
															88,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<motion.div
												className={"framer-x99w2q-container"}
												layoutDependency={layoutDependency}
												layoutId={"hmJbGC42s-container"}
											>
												{_jsx(stdin_default, {
													fDOQewoVL:
														"We serve a diverse range of clients including individuals, families, business owners, NRIs (Non-Resident Indians), and high-net-worth individuals. We customize our services to meet the specific needs of each client segment.",
													height: "100%",
													id: "hmJbGC42s",
													layoutId: "hmJbGC42s",
													nAIvabsq8:
														"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
													style: {
														width: "100%",
													},
													variant: "ald8i_pcX",
													width: "100%",
													wX23zzvm6: "Who are your typical clients?",
													wzShjY0g9: "Question 1 about the product goes here!",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={72}
											width={"343px"}
											{...addPropertyOverrides(
												{
													RW5DR0tov: {
														y:
															((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.y) || 0) +
															40 +
															0 +
															0 +
															176 +
															0 +
															0 +
															0 +
															176,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<motion.div
												className={"framer-1ipsouh-container"}
												layoutDependency={layoutDependency}
												layoutId={"N1gX62mGd-container"}
											>
												{_jsx(stdin_default, {
													fDOQewoVL:
														"Our approach is centered on our S.T.E.A.R commitment\u2014Service, Trust, Empathy, Advice, and Relationship. We prioritize building long-term relationships with our clients, offering personalized advice, and maintaining a deep understanding of your financial needs.",
													height: "100%",
													id: "N1gX62mGd",
													layoutId: "N1gX62mGd",
													nAIvabsq8:
														"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
													style: {
														width: "100%",
													},
													variant: "ald8i_pcX",
													width: "100%",
													wX23zzvm6: "What makes your services unique?",
													wzShjY0g9: "Question 1 about the product goes here!",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={72}
											width={"343px"}
											{...addPropertyOverrides(
												{
													RW5DR0tov: {
														y:
															((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.y) || 0) +
															40 +
															0 +
															0 +
															176 +
															0 +
															0 +
															0 +
															264,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<motion.div
												className={"framer-17t6n3d-container"}
												layoutDependency={layoutDependency}
												layoutId={"bYBKym8vr-container"}
											>
												{_jsx(stdin_default, {
													fDOQewoVL:
														"Yes, we have a global presence with expertise in handling KYC (Know Your Customer) regulations, taxation, and investment strategies for clients worldwide.",
													height: "100%",
													id: "bYBKym8vr",
													layoutId: "bYBKym8vr",
													nAIvabsq8:
														"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
													style: {
														width: "100%",
													},
													variant: "ald8i_pcX",
													width: "100%",
													wX23zzvm6: "Are your services available globally?",
													wzShjY0g9: "Question 1 about the product goes here!",
												})}
											</motion.div>
										</ComponentViewportProvider>
									</motion.div>
								</motion.div>
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-bAPt0.framer-1viiybv, .framer-bAPt0 .framer-1viiybv { display: block; }",
	".framer-bAPt0.framer-krsan6 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; overflow: visible; padding: 100px 120px 100px 120px; position: relative; width: 1440px; }",
	".framer-bAPt0 .framer-oqio6h { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 1200px; word-break: break-word; word-wrap: break-word; }",
	".framer-bAPt0 .framer-15451u { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-bAPt0 .framer-1nai6gd, .framer-bAPt0 .framer-1emurrl { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-bAPt0 .framer-1h7ebed-container, .framer-bAPt0 .framer-1xutir2-container, .framer-bAPt0 .framer-18ap0fr-container, .framer-bAPt0 .framer-biedbl-container, .framer-bAPt0 .framer-1ynuxch-container, .framer-bAPt0 .framer-1ipz5yv-container, .framer-bAPt0 .framer-fqz9pu-container, .framer-bAPt0 .framer-hkae7t-container, .framer-bAPt0 .framer-1d8f3kc-container, .framer-bAPt0 .framer-zqrdb1-container { flex: none; height: auto; position: relative; width: 580px; }",
	".framer-bAPt0 .framer-1uk2tvx { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: 100%; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-bAPt0 .framer-acv4hz-container, .framer-bAPt0 .framer-lsjjrt-container, .framer-bAPt0 .framer-rpwhxs-container, .framer-bAPt0 .framer-17cbgfy-container, .framer-bAPt0 .framer-1397qk-container, .framer-bAPt0 .framer-nff70i-container, .framer-bAPt0 .framer-x99w2q-container, .framer-bAPt0 .framer-1ipsouh-container, .framer-bAPt0 .framer-17t6n3d-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-bAPt0 .framer-19w6g9l { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-bAPt0 .framer-17h0jte { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 260px; word-break: break-word; word-wrap: break-word; }",
	".framer-bAPt0 .framer-v9u159 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 343px; }",
	".framer-bAPt0 .framer-1pgbb5z { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-bAPt0.framer-krsan6, .framer-bAPt0 .framer-15451u, .framer-bAPt0 .framer-1nai6gd, .framer-bAPt0 .framer-1uk2tvx, .framer-bAPt0 .framer-1emurrl, .framer-bAPt0 .framer-19w6g9l, .framer-bAPt0 .framer-v9u159, .framer-bAPt0 .framer-1pgbb5z { gap: 0px; } .framer-bAPt0.framer-krsan6 > * { margin: 0px; margin-bottom: calc(40px / 2); margin-top: calc(40px / 2); } .framer-bAPt0.framer-krsan6 > :first-child, .framer-bAPt0 .framer-1nai6gd > :first-child, .framer-bAPt0 .framer-1uk2tvx > :first-child, .framer-bAPt0 .framer-1emurrl > :first-child, .framer-bAPt0 .framer-19w6g9l > :first-child, .framer-bAPt0 .framer-v9u159 > :first-child, .framer-bAPt0 .framer-1pgbb5z > :first-child { margin-top: 0px; } .framer-bAPt0.framer-krsan6 > :last-child, .framer-bAPt0 .framer-1nai6gd > :last-child, .framer-bAPt0 .framer-1uk2tvx > :last-child, .framer-bAPt0 .framer-1emurrl > :last-child, .framer-bAPt0 .framer-19w6g9l > :last-child, .framer-bAPt0 .framer-v9u159 > :last-child, .framer-bAPt0 .framer-1pgbb5z > :last-child { margin-bottom: 0px; } .framer-bAPt0 .framer-15451u > * { margin: 0px; margin-left: calc(40px / 2); margin-right: calc(40px / 2); } .framer-bAPt0 .framer-15451u > :first-child { margin-left: 0px; } .framer-bAPt0 .framer-15451u > :last-child { margin-right: 0px; } .framer-bAPt0 .framer-1nai6gd > *, .framer-bAPt0 .framer-1uk2tvx > *, .framer-bAPt0 .framer-1emurrl > *, .framer-bAPt0 .framer-v9u159 > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-bAPt0 .framer-19w6g9l > * { margin: 0px; margin-bottom: calc(32px / 2); margin-top: calc(32px / 2); } .framer-bAPt0 .framer-1pgbb5z > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } }",
	".framer-bAPt0.framer-v-3m9p23.framer-krsan6 { padding: 100px 24px 100px 24px; width: 1200px; }",
	".framer-bAPt0.framer-v-3m9p23 .framer-15451u { gap: 24px; }",
	".framer-bAPt0.framer-v-3m9p23 .framer-1uk2tvx { height: 456px; order: 2; }",
	".framer-bAPt0.framer-v-3m9p23 .framer-1ipz5yv-container, .framer-bAPt0.framer-v-3m9p23 .framer-fqz9pu-container, .framer-bAPt0.framer-v-3m9p23 .framer-hkae7t-container, .framer-bAPt0.framer-v-3m9p23 .framer-1d8f3kc-container, .framer-bAPt0.framer-v-3m9p23 .framer-zqrdb1-container, .framer-bAPt0.framer-v-sh16l .framer-oqio6h { width: 100%; }",
	".framer-bAPt0.framer-v-3m9p23 .framer-1emurrl { order: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-bAPt0.framer-v-3m9p23 .framer-15451u { gap: 0px; } .framer-bAPt0.framer-v-3m9p23 .framer-15451u > * { margin: 0px; margin-left: calc(24px / 2); margin-right: calc(24px / 2); } .framer-bAPt0.framer-v-3m9p23 .framer-15451u > :first-child { margin-left: 0px; } .framer-bAPt0.framer-v-3m9p23 .framer-15451u > :last-child { margin-right: 0px; } }",
	".framer-bAPt0.framer-v-sh16l.framer-krsan6 { padding: 40px 24px 40px 24px; width: 810px; }",
	".framer-bAPt0.framer-v-sh16l .framer-15451u { align-content: center; align-items: center; flex-direction: column; gap: 16px; }",
	".framer-bAPt0.framer-v-sh16l .framer-1nai6gd { align-content: center; align-items: center; flex: none; gap: 16px; max-width: 762px; width: 100%; }",
	".framer-bAPt0.framer-v-sh16l .framer-1uk2tvx { align-content: center; align-items: center; flex: none; gap: 16px; height: 456px; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-bAPt0.framer-v-sh16l .framer-15451u, .framer-bAPt0.framer-v-sh16l .framer-1nai6gd, .framer-bAPt0.framer-v-sh16l .framer-1uk2tvx { gap: 0px; } .framer-bAPt0.framer-v-sh16l .framer-15451u > *, .framer-bAPt0.framer-v-sh16l .framer-1nai6gd > *, .framer-bAPt0.framer-v-sh16l .framer-1uk2tvx > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } .framer-bAPt0.framer-v-sh16l .framer-15451u > :first-child, .framer-bAPt0.framer-v-sh16l .framer-1nai6gd > :first-child, .framer-bAPt0.framer-v-sh16l .framer-1uk2tvx > :first-child { margin-top: 0px; } .framer-bAPt0.framer-v-sh16l .framer-15451u > :last-child, .framer-bAPt0.framer-v-sh16l .framer-1nai6gd > :last-child, .framer-bAPt0.framer-v-sh16l .framer-1uk2tvx > :last-child { margin-bottom: 0px; } }",
	".framer-bAPt0.framer-v-1k04bgg.framer-krsan6 { padding: 40px 0px 40px 0px; width: min-content; }",
];
var FramerQz_wO8lJ9 = withCSS(Component, css, "framer-bAPt0");
var stdin_default2 = FramerQz_wO8lJ9;
FramerQz_wO8lJ9.displayName = "FAQs";
FramerQz_wO8lJ9.defaultProps = {
	height: 853,
	width: 1440,
};
addPropertyControls(FramerQz_wO8lJ9, {
	variant: {
		options: ["QoyiWMkdj", "VakuvyNg8", "GyWV9AsFb", "RW5DR0tov"],
		optionTitles: ["Desktop", "Desktop-sm", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerQz_wO8lJ9,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Plus Jakarta Sans",
					source: "google",
					style: "normal",
					url: "/fonts/LDIbaomQNQcsA88c7O9yZ4KMCoOg4IA6-91aHEjcWuA_TknNTxXUEKi4Rw.woff2",
					weight: "700",
				},
			],
		},
		...QuestionFAQFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:fa-qs
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "GyWV9AsFb",
	xl: "QoyiWMkdj",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"af460206e137e8d824a96fddb1ea9788b0ffdc50cd99b3f451f16d44c1636491"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaQsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"af460206e137e8d824a96fddb1ea9788b0ffdc50cd99b3f451f16d44c1636491"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var fa_qs_default = ComponentWithRoot;
export { fa_qs_default as default };
