// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project af460206e137e8d8 "Sapient", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Desktop-sm' | 'Tablet' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-M7BJUZ2O.js";
import { routes } from "./chunks/chunk-PZVC6U2W.js";

// virtual:global
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:/framer-cms/modules/DB7b8PMb3fYoVjD81uqc/4VzS5kCuG8inaHScKyrj/rwOne2Nuu.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var RichTextWithFX = withFX(RichText);
var PolaroidCardFonts = getFonts(stdin_default);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var cycleOrder = ["lNtxfeDt5", "EjkhvA0Af", "FHksCE2HQ"];
var serializationHash = "framer-uK4a2";
var variantClassNames = {
	EjkhvA0Af: "framer-v-14bgn48",
	FHksCE2HQ: "framer-v-1v80ge1",
	lNtxfeDt5: "framer-v-cg3kgk",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 60,
};
var transition2 = {
	damping: 40,
	delay: 0,
	mass: 1,
	stiffness: 150,
	type: "spring",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 40,
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var transition3 = {
	damping: 40,
	delay: 0.2,
	mass: 1,
	stiffness: 150,
	type: "spring",
};
var transition4 = {
	damping: 40,
	delay: 0.3,
	mass: 1,
	stiffness: 150,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Desktop-sm": "EjkhvA0Af",
	Desktop: "lNtxfeDt5",
	Tablet: "FHksCE2HQ",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "lNtxfeDt5",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "lNtxfeDt5",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-cg3kgk",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"lNtxfeDt5"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(245, 242, 235)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								EjkhvA0Af: {
									"data-framer-name": "Desktop-sm",
								},
								FHksCE2HQ: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-14atbbq"}
							data-framer-name={"Frame 1348"}
							layoutDependency={layoutDependency}
							layoutId={"xBm2VGAhV"}
						>
							<RichTextWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-11f01t1"}
								data-framer-name={"We\u2019re Global!"}
								fonts={["GF;Plus Jakarta Sans-700"]}
								layoutDependency={layoutDependency}
								layoutId={"mYgg6Sruy"}
								style={{
									"--extracted-r6o4lv": "rgb(23, 35, 30)",
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										dir={"auto"}
										style={{
											"--font-selector": "R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
											"--framer-font-family":
												'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
											"--framer-font-size": "40px",
											"--framer-font-weight": "700",
											"--framer-line-height": "135%",
											"--framer-text-alignment": "center",
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(23, 35, 30))",
										}}
									>
										{"We\u2019re Global!"}
									</motion.p>
								</React.Fragment>
							</RichTextWithFX>
							<motion.div
								className={"framer-1r6jbkn"}
								data-framer-name={"Frame 1430105583"}
								layoutDependency={layoutDependency}
								layoutId={"mC4W5WlsW"}
							>
								<motion.div
									className={"framer-k2xx39"}
									data-framer-name={"Frame 1430105583"}
									layoutDependency={layoutDependency}
									layoutId={"w7dqkzKaB"}
								>
									<ComponentViewportProvider
										height={546}
										width={`max((min(${componentViewport?.width || "100vw"} - 240px, 1200px) - 432px) / 2, 1px)`}
										y={
											(componentViewport?.y || 0) +
											100 +
											0 +
											0 +
											310 +
											0 +
											0 +
											0
										}
										{...addPropertyOverrides(
											{
												EjkhvA0Af: {
													width: `max((min(${componentViewport?.width || "100vw"} - 48px, 1200px) - 32px) / 3, 1px)`,
												},
												FHksCE2HQ: {
													width: `min(min(${componentViewport?.width || "100vw"} - 48px, 1200px), 762px)`,
													y:
														(componentViewport?.y || 0) +
														40 +
														0 +
														0 +
														310 +
														0 +
														0 +
														0 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											__framer__animate={{
												transition: transition2,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation1}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0.5}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-2rf0fu-container"}
											layoutDependency={layoutDependency}
											layoutId={"wkx7IMvf4-container"}
											nodeId={"wkx7IMvf4"}
											rendersWithMotion={true}
											scopeId={"rwOne2Nuu"}
										>
											{_jsx(stdin_default, {
												height: "100%",
												id: "wkx7IMvf4",
												layoutId: "wkx7IMvf4",
												style: {
													width: "100%",
												},
												variant: matchVariant("AGAxxJwwW"),
												width: "100%",
												...addPropertyOverrides(
													{
														EjkhvA0Af: {
															style: {
																height: "100%",
																width: "100%",
															},
														},
														FHksCE2HQ: {
															style: {
																maxWidth: "100%",
																width: "100%",
															},
															variant: matchVariant("tu7RbsB8F"),
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={546}
										width={`max((min(${componentViewport?.width || "100vw"} - 240px, 1200px) - 432px) / 2, 1px)`}
										y={
											(componentViewport?.y || 0) +
											100 +
											0 +
											0 +
											310 +
											0 +
											0 +
											0
										}
										{...addPropertyOverrides(
											{
												EjkhvA0Af: {
													width: `max((min(${componentViewport?.width || "100vw"} - 48px, 1200px) - 32px) / 3, 1px)`,
												},
												FHksCE2HQ: {
													width: `min(min(${componentViewport?.width || "100vw"} - 48px, 1200px), 762px)`,
													y:
														(componentViewport?.y || 0) +
														40 +
														0 +
														0 +
														310 +
														0 +
														0 +
														0 +
														570,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											__framer__animate={{
												transition: transition3,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation1}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0.5}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-1wfn7a-container"}
											layoutDependency={layoutDependency}
											layoutId={"e2qMXC1ii-container"}
											nodeId={"e2qMXC1ii"}
											rendersWithMotion={true}
											scopeId={"rwOne2Nuu"}
										>
											{_jsx(stdin_default, {
												height: "100%",
												id: "e2qMXC1ii",
												layoutId: "e2qMXC1ii",
												style: {
													width: "100%",
												},
												variant: matchVariant("dLAre3_fZ"),
												width: "100%",
												...addPropertyOverrides(
													{
														FHksCE2HQ: {
															style: {
																maxWidth: "100%",
																width: "100%",
															},
															variant: matchVariant("OzZKAl7UC"),
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={546}
										width={"384px"}
										y={
											(componentViewport?.y || 0) +
											100 +
											0 +
											0 +
											310 +
											0 +
											0 +
											0
										}
										{...addPropertyOverrides(
											{
												EjkhvA0Af: {
													width: `max((min(${componentViewport?.width || "100vw"} - 48px, 1200px) - 32px) / 3, 1px)`,
												},
												FHksCE2HQ: {
													width: `min(min(${componentViewport?.width || "100vw"} - 48px, 1200px), 762px)`,
													y:
														(componentViewport?.y || 0) +
														40 +
														0 +
														0 +
														310 +
														0 +
														0 +
														0 +
														1140,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											__framer__animate={{
												transition: transition4,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation1}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0.5}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-1xtl29a-container"}
											layoutDependency={layoutDependency}
											layoutId={"thUkCTMuG-container"}
											nodeId={"thUkCTMuG"}
											rendersWithMotion={true}
											scopeId={"rwOne2Nuu"}
										>
											{_jsx(stdin_default, {
												height: "100%",
												id: "thUkCTMuG",
												layoutId: "thUkCTMuG",
												style: {
													width: "100%",
												},
												variant: matchVariant("Jn8Onkj4r"),
												width: "100%",
												...addPropertyOverrides(
													{
														FHksCE2HQ: {
															style: {
																maxWidth: "100%",
																width: "100%",
															},
															variant: matchVariant("YZlj3WQbR"),
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-uK4a2.framer-odwvuo, .framer-uK4a2 .framer-odwvuo { display: block; }",
	".framer-uK4a2.framer-cg3kgk { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 100px 120px 100px 120px; position: relative; width: 1440px; }",
	".framer-uK4a2 .framer-14atbbq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-uK4a2 .framer-11f01t1 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 1200px; word-break: break-word; word-wrap: break-word; }",
	".framer-uK4a2 .framer-1r6jbkn { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-uK4a2 .framer-k2xx39 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; max-width: 1200px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-uK4a2 .framer-2rf0fu-container, .framer-uK4a2 .framer-1wfn7a-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-uK4a2 .framer-1xtl29a-container { flex: none; height: auto; position: relative; width: 384px; }",
	".framer-uK4a2.framer-v-14bgn48.framer-cg3kgk { padding: 100px 24px 100px 24px; width: 1200px; }",
	".framer-uK4a2.framer-v-14bgn48 .framer-14atbbq { max-width: 1200px; }",
	".framer-uK4a2.framer-v-14bgn48 .framer-k2xx39 { gap: 16px; }",
	".framer-uK4a2.framer-v-14bgn48 .framer-2rf0fu-container { align-self: stretch; }",
	".framer-uK4a2.framer-v-14bgn48 .framer-1xtl29a-container { flex: 1 0 0px; width: 1px; }",
	".framer-uK4a2.framer-v-1v80ge1.framer-cg3kgk { padding: 40px 24px 40px 24px; width: 810px; }",
	".framer-uK4a2.framer-v-1v80ge1 .framer-11f01t1 { width: 100%; }",
	".framer-uK4a2.framer-v-1v80ge1 .framer-k2xx39 { align-content: center; align-items: center; flex-direction: column; }",
	".framer-uK4a2.framer-v-1v80ge1 .framer-2rf0fu-container, .framer-uK4a2.framer-v-1v80ge1 .framer-1wfn7a-container { flex: none; max-width: 762px; width: 100%; }",
	".framer-uK4a2.framer-v-1v80ge1 .framer-1xtl29a-container { max-width: 762px; width: 100%; }",
];
var FramerrwOne2Nuu = withCSS(Component, css, "framer-uK4a2");
var stdin_default2 = FramerrwOne2Nuu;
FramerrwOne2Nuu.displayName = "Global";
FramerrwOne2Nuu.defaultProps = {
	height: 841,
	width: 1440,
};
addPropertyControls(FramerrwOne2Nuu, {
	variant: {
		options: ["lNtxfeDt5", "EjkhvA0Af", "FHksCE2HQ"],
		optionTitles: ["Desktop", "Desktop-sm", "Tablet"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerrwOne2Nuu,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Plus Jakarta Sans",
					source: "google",
					style: "normal",
					uiFamilyName: "Plus Jakarta Sans",
					url: "/fonts/LDIbaomQNQcsA88c7O9yZ4KMCoOg4IA6-91aHEjcWuA_TknNTxXUEKi4Rw.woff2",
					weight: "700",
				},
			],
		},
		...PolaroidCardFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerrwOne2Nuu.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:global
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "FHksCE2HQ",
	xl: "EjkhvA0Af",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"af460206e137e8d824a96fddb1ea9788b0ffdc50cd99b3f451f16d44c1636491"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders GlobalFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"af460206e137e8d824a96fddb1ea9788b0ffdc50cd99b3f451f16d44c1636491"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var global_default = ComponentWithRoot;
export { global_default as default };
