// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project af460206e137e8d8 "Sapient", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Pressed' | 'm-Default' | 'm-Pressed' // Variant
 * title?: string // Title
 * click?: Function // Click
}} Props

 */
import { routes } from "./chunks/chunk-PZVC6U2W.js";

// virtual:tag
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:/framer-cms/modules/sgQKjc1NpxYcA10eczzv/YcLZMIqOBhd3XRVGp5RW/tHWfN6uYs.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["UMZx4GDww", "UzjHbzhsh", "t_DTTAl6R", "QuGOFm7qu"];
var serializationHash = "framer-YyKoO";
var variantClassNames = {
	QuGOFm7qu: "framer-v-lsnhlr",
	t_DTTAl6R: "framer-v-ld5nhg",
	UMZx4GDww: "framer-v-mhgrhe",
	UzjHbzhsh: "framer-v-bfxijx",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	"m-Default": "t_DTTAl6R",
	"m-Pressed": "QuGOFm7qu",
	Default: "UMZx4GDww",
	Pressed: "UzjHbzhsh",
};
var getProps = ({ click, height, id, title, width, ...props }) => {
	var _ref, _humanReadableVariantMap_props_variant, _ref1;
	return {
		...props,
		HkrkfHQ5l:
			(_ref = title !== null && title !== void 0 ? title : props.HkrkfHQ5l) !==
				null && _ref !== void 0
				? _ref
				: "HNI/UHNI",
		Lnr3n1Its: click !== null && click !== void 0 ? click : props.Lnr3n1Its,
		variant:
			(_ref1 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref1 !== void 0
				? _ref1
				: "UMZx4GDww",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className,
		layoutId,
		variant,
		HkrkfHQ5l,
		Lnr3n1Its,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "UMZx4GDww",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap18t6hj4 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (Lnr3n1Its) {
			const res = await Lnr3n1Its(...args);
			if (res === false) return false;
		}
		setVariant("UzjHbzhsh");
	});
	const onTapalihzv = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (Lnr3n1Its) {
			const res = await Lnr3n1Its(...args);
			if (res === false) return false;
		}
		setVariant("QuGOFm7qu");
	});
	const onTap1t8z4dc = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (Lnr3n1Its) {
			const res = await Lnr3n1Its(...args);
			if (res === false) return false;
		}
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-mhgrhe",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Default"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"UMZx4GDww"}
						onTap={onTap18t6hj4}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							"--border-bottom-width": "1px",
							"--border-color": "rgb(164, 207, 107)",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor: "rgba(0, 0, 0, 0)",
							borderBottomLeftRadius: 44,
							borderBottomRightRadius: 44,
							borderTopLeftRadius: 44,
							borderTopRightRadius: 44,
							boxShadow: "0px 4px 12px 0px rgba(0, 0, 0, 0.07999999821186066)",
							...style,
						}}
						variants={{
							QuGOFm7qu: {
								"--border-bottom-width": "0px",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
								backgroundColor: "rgb(29, 62, 48)",
							},
							UzjHbzhsh: {
								"--border-bottom-width": "0px",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
								backgroundColor: "rgb(29, 62, 48)",
							},
						}}
						{...addPropertyOverrides(
							{
								QuGOFm7qu: {
									"data-framer-name": "m-Pressed",
									onTap: onTap1t8z4dc,
								},
								t_DTTAl6R: {
									"data-framer-name": "m-Default",
									onTap: onTapalihzv,
								},
								UzjHbzhsh: {
									"data-framer-name": "Pressed",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-hdm4bf"}
							data-framer-name={"HNI/UHNI"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"nCFRMB1YZ"}
							style={{
								"--extracted-r6o4lv": "rgb(29, 40, 66)",
								"--framer-paragraph-spacing": "0px",
							}}
							text={HkrkfHQ5l}
							variants={{
								QuGOFm7qu: {
									"--extracted-r6o4lv": "rgb(255, 255, 255)",
								},
								UzjHbzhsh: {
									"--extracted-r6o4lv": "rgb(255, 255, 255)",
								},
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									QuGOFm7qu: {
										children: (
											<React.Fragment>
												<motion.p
													style={{
														"--framer-font-size": "12px",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(255, 255, 255))",
													}}
												>
													{"HNI/UHNI"}
												</motion.p>
											</React.Fragment>
										),
									},
									t_DTTAl6R: {
										children: (
											<React.Fragment>
												<motion.p
													style={{
														"--framer-font-size": "12px",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(29, 40, 66))",
													}}
												>
													{"HNI/UHNI"}
												</motion.p>
											</React.Fragment>
										),
									},
									UzjHbzhsh: {
										children: (
											<React.Fragment>
												<motion.p
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(255, 255, 255))",
													}}
												>
													{"HNI/UHNI"}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(29, 40, 66))",
									}}
								>
									{"HNI/UHNI"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-YyKoO.framer-vh63lz, .framer-YyKoO .framer-vh63lz { display: block; }",
	".framer-YyKoO.framer-mhgrhe { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 12px 16px 12px 16px; position: relative; width: min-content; }",
	".framer-YyKoO .framer-hdm4bf { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-YyKoO.framer-mhgrhe { gap: 0px; } .framer-YyKoO.framer-mhgrhe > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-YyKoO.framer-mhgrhe > :first-child { margin-left: 0px; } .framer-YyKoO.framer-mhgrhe > :last-child { margin-right: 0px; } }",
	".framer-YyKoO.framer-v-ld5nhg.framer-mhgrhe, .framer-YyKoO.framer-v-lsnhlr.framer-mhgrhe { padding: 8px 12px 8px 12px; }",
	'.framer-YyKoO[data-border="true"]::after, .framer-YyKoO [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramertHWfN6uYs = withCSS(Component, css, "framer-YyKoO");
var stdin_default = FramertHWfN6uYs;
FramertHWfN6uYs.displayName = "Tag";
FramertHWfN6uYs.defaultProps = {
	height: 43,
	width: 106,
};
addPropertyControls(FramertHWfN6uYs, {
	variant: {
		options: ["UMZx4GDww", "UzjHbzhsh", "t_DTTAl6R", "QuGOFm7qu"],
		optionTitles: ["Default", "Pressed", "m-Default", "m-Pressed"],
		title: "Variant",
		type: ControlType.Enum,
	},
	HkrkfHQ5l: {
		defaultValue: "HNI/UHNI",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	Lnr3n1Its: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramertHWfN6uYs,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "/fonts/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "/fonts/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "/fonts/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "/fonts/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "/fonts/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "/fonts/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "/fonts/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:tag
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "QuGOFm7qu",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"af460206e137e8d824a96fddb1ea9788b0ffdc50cd99b3f451f16d44c1636491"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TagFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"af460206e137e8d824a96fddb1ea9788b0ffdc50cd99b3f451f16d44c1636491"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var tag_default = ComponentWithRoot;
export { tag_default as default };
