// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project af460206e137e8d8 "Sapient", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Desktop-sm' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-PZVC6U2W.js";

// virtual:blogs-text
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:/framer-cms/modules/EhIxGuf8JVVEFTlHunIB/KAFvtFs3ccXLfuZHyUeH/tnmLbtM8H.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["KI5Vv8ATL", "v6s6PB9H6", "Ao7atSuKe", "lMgCXXKFw"];
var serializationHash = "framer-tQqkK";
var variantClassNames = {
	Ao7atSuKe: "framer-v-3xgg14",
	KI5Vv8ATL: "framer-v-gmi0zn",
	lMgCXXKFw: "framer-v-1bluoqf",
	v6s6PB9H6: "framer-v-18v3lk1",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Desktop-sm": "v6s6PB9H6",
	Desktop: "KI5Vv8ATL",
	Phone: "lMgCXXKFw",
	Tablet: "Ao7atSuKe",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "KI5Vv8ATL",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "KI5Vv8ATL",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-gmi0zn",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"KI5Vv8ATL"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								Ao7atSuKe: {
									"data-framer-name": "Tablet",
								},
								lMgCXXKFw: {
									"data-framer-name": "Phone",
								},
								v6s6PB9H6: {
									"data-framer-name": "Desktop-sm",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-b7yax2"}
							data-framer-name={"Explore blogs"}
							fonts={["GF;Plus Jakarta Sans-500"]}
							layoutDependency={layoutDependency}
							layoutId={"MJ7LihSmT"}
							style={{
								"--extracted-r6o4lv": "rgb(15, 23, 42)",
								"--framer-paragraph-spacing": "0px",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									lMgCXXKFw: {
										children: (
											<React.Fragment>
												<motion.p
													dir={"auto"}
													style={{
														"--font-selector":
															"R0Y7UGx1cyBKYWthcnRhIFNhbnMtNTAw",
														"--framer-font-family":
															'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
														"--framer-font-size": "24px",
														"--framer-font-weight": "500",
														"--framer-letter-spacing": "0.01em",
														"--framer-line-height": "120%",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(15, 23, 42))",
													}}
												>
													{"Explore blogs"}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									dir={"auto"}
									style={{
										"--font-selector": "R0Y7UGx1cyBKYWthcnRhIFNhbnMtNTAw",
										"--framer-font-family":
											'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
										"--framer-font-size": "56px",
										"--framer-font-weight": "500",
										"--framer-letter-spacing": "0.01em",
										"--framer-line-height": "120%",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(15, 23, 42))",
									}}
								>
									{"Explore blogs"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-m565p4"}
							data-framer-name={
								"Manage your investments using data-driven strategies with transparent track records. Backtest & check with top-tier tools and make money smartly"
							}
							fonts={["GF;Satoshi-500"]}
							layoutDependency={layoutDependency}
							layoutId={"i6KM2MKAG"}
							style={{
								"--extracted-r6o4lv": "rgb(51, 65, 85)",
								"--framer-paragraph-spacing": "0px",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									lMgCXXKFw: {
										children: (
											<React.Fragment>
												<motion.p
													dir={"auto"}
													style={{
														"--font-selector": "R0Y7U2F0b3NoaS01MDA=",
														"--framer-font-family":
															'"Satoshi", "Satoshi Placeholder", sans-serif',
														"--framer-font-size": "12px",
														"--framer-font-weight": "500",
														"--framer-letter-spacing": "0.01em",
														"--framer-line-height": "150%",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(51, 65, 85))",
													}}
												>
													{
														"Manage your investments using data-driven strategies with transparent track records. Backtest & check with top-tier tools and make money smartly"
													}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									dir={"auto"}
									style={{
										"--font-selector": "R0Y7U2F0b3NoaS01MDA=",
										"--framer-font-family":
											'"Satoshi", "Satoshi Placeholder", sans-serif',
										"--framer-font-weight": "500",
										"--framer-letter-spacing": "0.01em",
										"--framer-line-height": "150%",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(51, 65, 85))",
									}}
								>
									{
										"Manage your investments using data-driven strategies with transparent track records. Backtest & check with top-tier tools and make money smartly"
									}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-tQqkK.framer-iblz43, .framer-tQqkK .framer-iblz43 { display: block; }",
	".framer-tQqkK.framer-gmi0zn { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; max-width: 1440px; overflow: visible; padding: 0px 120px 0px 120px; position: relative; width: 1440px; }",
	".framer-tQqkK .framer-b7yax2 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-tQqkK .framer-m565p4 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 621px; word-break: break-word; word-wrap: break-word; }",
	".framer-tQqkK.framer-v-18v3lk1.framer-gmi0zn { max-width: 1200px; padding: 0px 120px 0px 24px; width: 1200px; }",
	".framer-tQqkK.framer-v-3xgg14.framer-gmi0zn { max-width: 810px; padding: 0px 24px 0px 24px; width: 810px; }",
	".framer-tQqkK.framer-v-1bluoqf.framer-gmi0zn { max-width: 390px; padding: 0px 24px 0px 24px; width: 390px; }",
	".framer-tQqkK.framer-v-1bluoqf .framer-m565p4 { width: 312px; }",
];
var FramertnmLbtM8H = withCSS(Component, css, "framer-tQqkK");
var stdin_default = FramertnmLbtM8H;
FramertnmLbtM8H.displayName = "BlogsText";
FramertnmLbtM8H.defaultProps = {
	height: 131,
	width: 1440,
};
addPropertyControls(FramertnmLbtM8H, {
	variant: {
		options: ["KI5Vv8ATL", "v6s6PB9H6", "Ao7atSuKe", "lMgCXXKFw"],
		optionTitles: ["Desktop", "Desktop-sm", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramertnmLbtM8H,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Plus Jakarta Sans",
					source: "google",
					style: "normal",
					uiFamilyName: "Plus Jakarta Sans",
					url: "/fonts/LDIbaomQNQcsA88c7O9yZ4KMCoOg4IA6-91aHEjcWuA_m07NTxXUEKi4Rw.woff2",
					weight: "500",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:blogs-text
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "lMgCXXKFw",
	md: "Ao7atSuKe",
	xl: "KI5Vv8ATL",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"af460206e137e8d824a96fddb1ea9788b0ffdc50cd99b3f451f16d44c1636491"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BlogsTextFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"af460206e137e8d824a96fddb1ea9788b0ffdc50cd99b3f451f16d44c1636491"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var blogs_text_default = ComponentWithRoot;
export { blogs_text_default as default };
