// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project af460206e137e8d8 "Sapient", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Desktop-sm' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-PZVC6U2W.js";

// virtual:kym-text
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:/framer-cms/modules/4wfqYDPu6GrPnBN02mR3/YiID1psyiM19s9b50U0Q/SdWwOYhE6.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["sFzNLFlbM", "IuLa2mcrN", "j2l83nAct", "HJS7wysHa"];
var serializationHash = "framer-BRlTO";
var variantClassNames = {
	HJS7wysHa: "framer-v-h7u8z9",
	IuLa2mcrN: "framer-v-aeo1gn",
	j2l83nAct: "framer-v-1sh94dl",
	sFzNLFlbM: "framer-v-1txto9e",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Desktop-sm": "IuLa2mcrN",
	Desktop: "sFzNLFlbM",
	Phone: "HJS7wysHa",
	Tablet: "j2l83nAct",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "sFzNLFlbM",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "sFzNLFlbM",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1txto9e",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"sFzNLFlbM"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								HJS7wysHa: {
									"data-framer-name": "Phone",
								},
								IuLa2mcrN: {
									"data-framer-name": "Desktop-sm",
								},
								j2l83nAct: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-iruy1x"}
							data-framer-name={"KYM : Know your manager"}
							fonts={["GF;Plus Jakarta Sans-700"]}
							layoutDependency={layoutDependency}
							layoutId={"jSAXDVOy3"}
							style={{
								"--extracted-r6o4lv": "rgb(15, 23, 42)",
								"--framer-paragraph-spacing": "0px",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									HJS7wysHa: {
										children: (
											<React.Fragment>
												<motion.p
													dir={"auto"}
													style={{
														"--font-selector":
															"R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
														"--framer-font-family":
															'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
														"--framer-font-size": "24px",
														"--framer-font-weight": "700",
														"--framer-letter-spacing": "0.01em",
														"--framer-line-height": "120%",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(15, 23, 42))",
													}}
												>
													{"KYM : Know your manager"}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									dir={"auto"}
									style={{
										"--font-selector": "R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
										"--framer-font-family":
											'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
										"--framer-font-size": "56px",
										"--framer-font-weight": "700",
										"--framer-letter-spacing": "0.01em",
										"--framer-line-height": "120%",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(15, 23, 42))",
									}}
								>
									{"KYM : Know your manager"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-xjcwov"}
							data-framer-name={
								"Every week we invite some of the most influential people from around the the world to discuss about the future of finance in india and how important financial knowledge really is."
							}
							fonts={["GF;Satoshi-500"]}
							layoutDependency={layoutDependency}
							layoutId={"sEDIeXA74"}
							style={{
								"--extracted-r6o4lv": "rgb(51, 65, 85)",
								"--framer-paragraph-spacing": "0px",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									HJS7wysHa: {
										children: (
											<React.Fragment>
												<motion.p
													dir={"auto"}
													style={{
														"--font-selector": "R0Y7U2F0b3NoaS01MDA=",
														"--framer-font-family":
															'"Satoshi", "Satoshi Placeholder", sans-serif',
														"--framer-font-size": "12px",
														"--framer-font-weight": "500",
														"--framer-letter-spacing": "0.01em",
														"--framer-line-height": "150%",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(51, 65, 85))",
													}}
												>
													{
														"Every week we invite some of the most influential people from around the the world to discuss about the future of finance in india and how important financial knowledge really is."
													}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									dir={"auto"}
									style={{
										"--font-selector": "R0Y7U2F0b3NoaS01MDA=",
										"--framer-font-family":
											'"Satoshi", "Satoshi Placeholder", sans-serif',
										"--framer-font-weight": "500",
										"--framer-letter-spacing": "0.01em",
										"--framer-line-height": "150%",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(51, 65, 85))",
									}}
								>
									{
										"Every week we invite some of the most influential people from around the the world to discuss about the future of finance in india and how important financial knowledge really is."
									}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-BRlTO.framer-69bgkp, .framer-BRlTO .framer-69bgkp { display: block; }",
	".framer-BRlTO.framer-1txto9e { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; max-width: 100%; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-BRlTO .framer-iruy1x { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; max-width: 929px; word-break: break-word; word-wrap: break-word; }",
	".framer-BRlTO .framer-xjcwov { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; max-width: 757px; word-break: break-word; word-wrap: break-word; }",
	".framer-BRlTO.framer-v-aeo1gn.framer-1txto9e { padding: 0px; width: 100%; }",
	".framer-BRlTO.framer-v-aeo1gn .framer-iruy1x, .framer-BRlTO.framer-v-1sh94dl .framer-iruy1x, .framer-BRlTO.framer-v-1sh94dl .framer-xjcwov, .framer-BRlTO.framer-v-h7u8z9 .framer-iruy1x, .framer-BRlTO.framer-v-h7u8z9 .framer-xjcwov { width: 100%; }",
	".framer-BRlTO.framer-v-1sh94dl.framer-1txto9e { padding: 0px; width: 100%; max-width: 100%; }",
	".framer-BRlTO.framer-v-h7u8z9.framer-1txto9e { gap: 8px; width: 100%; max-width: 100%; }",
];
var FramerSdWwOYhE6 = withCSS(Component, css, "framer-BRlTO");
var stdin_default = FramerSdWwOYhE6;
FramerSdWwOYhE6.displayName = "KYM-Text";
FramerSdWwOYhE6.defaultProps = {
	height: 131,
	width: 1200,
};
addPropertyControls(FramerSdWwOYhE6, {
	variant: {
		options: ["sFzNLFlbM", "IuLa2mcrN", "j2l83nAct", "HJS7wysHa"],
		optionTitles: ["Desktop", "Desktop-sm", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerSdWwOYhE6,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Plus Jakarta Sans",
					source: "google",
					style: "normal",
					uiFamilyName: "Plus Jakarta Sans",
					url: "/fonts/LDIbaomQNQcsA88c7O9yZ4KMCoOg4IA6-91aHEjcWuA_TknNTxXUEKi4Rw.woff2",
					weight: "700",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:kym-text
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "HJS7wysHa",
	md: "j2l83nAct",
	xl: "IuLa2mcrN",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"af460206e137e8d824a96fddb1ea9788b0ffdc50cd99b3f451f16d44c1636491"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders KymTextFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"af460206e137e8d824a96fddb1ea9788b0ffdc50cd99b3f451f16d44c1636491"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var kym_text_default = ComponentWithRoot;
export { kym_text_default as default };
