// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project af460206e137e8d8 "Sapient", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' | 'Phone Open' | 'Variant 5' | 'Variant 6' // Variant
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-BUBOLMCJ.js";
import { routes } from "./chunks/chunk-PZVC6U2W.js";

// virtual:navigation
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:/framer-cms/modules/4USe4qVCZjMoUn9hnvIF/Nq2P1aiIn5797tNwuU2u/dZbRlifrz.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Floating,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image as Image1,
	Link,
	RichText,
	SVG,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOverlayState,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import {
	AnimatePresence,
	LayoutGroup,
	motion,
	MotionConfigContext,
} from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:/framer-cms/modules/iXsi5tnCa9niAjgus4s8/e2KFSw8Dm6HuHnv1AvQY/nvKqLENyr.js
import { fontStore } from "unframer";
fontStore.loadFonts([]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [],
	},
];
var css2 = [
	".framer-Wb3hd .framer-styles-preset-14n2j3:not(.rich-text-wrapper), .framer-Wb3hd .framer-styles-preset-14n2j3.rich-text-wrapper a { --framer-link-current-text-color: #111111; --framer-link-current-text-decoration: underline; --framer-link-hover-text-color: #000000; --framer-link-hover-text-decoration: underline; --framer-link-text-color: #1f2a3c; --framer-link-text-decoration: none; }",
];
var className2 = "framer-Wb3hd";

// /:/framer-cms/modules/4USe4qVCZjMoUn9hnvIF/Nq2P1aiIn5797tNwuU2u/dZbRlifrz.js
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = [
	"hUMCu1JaQ",
	"zvqvmgi_X",
	"YmfvgTG50",
	"tpyWFivQj",
	"DRm9pRmsR",
];
var serializationHash = "framer-e9rxN";
var variantClassNames = {
	DRm9pRmsR: "framer-v-184jsh9",
	hUMCu1JaQ: "framer-v-dxvjkb",
	tpyWFivQj: "framer-v-qqp9ex",
	YmfvgTG50: "framer-v-1uivldt",
	zvqvmgi_X: "framer-v-ou95mp",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	duration: 0.45,
	ease: [0.22, 1, 0.36, 1],
	type: "tween",
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var Overlay = ({
	children,
	blockDocumentScrolling,
	dismissWithEsc,
	enabled = true,
}) => {
	const [visible, setVisible] = useOverlayState({
		blockDocumentScrolling,
		dismissWithEsc: enabled && dismissWithEsc,
	});
	return children({
		hide: () => setVisible(false),
		show: () => setVisible(true),
		toggle: () => setVisible(!visible),
		visible: enabled && visible,
	});
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Phone Open": "YmfvgTG50",
	"Variant 5": "tpyWFivQj",
	"Variant 6": "DRm9pRmsR",
	Desktop: "hUMCu1JaQ",
	Phone: "zvqvmgi_X",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "hUMCu1JaQ",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "hUMCu1JaQ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback } =
		useActiveVariantCallback(baseVariant);
	const onTap13elrgn = ({ overlay }) =>
		activeVariantCallback(async (...args) => {
			overlay.show();
		});
	const onMouseEnter13elrgn = ({ overlay }) =>
		activeVariantCallback(async (...args) => {
			overlay.show();
		});
	// Open immediately — a delayed setVariant is cancelled by
	// useActiveVariantCallback's rejectPending on re-render/effects.
	const PHONE_CLOSED = "zvqvmgi_X";
	const PHONE_OPEN = "YmfvgTG50";
	const RESOURCES_OPEN = "tpyWFivQj";
	const INVESTMENT_OPEN = "DRm9pRmsR";

	const onTapnx26yq = () => {
		setVariant(PHONE_OPEN);
	};
	const onTap1x5cmto = () => {
		setVariant(PHONE_CLOSED);
	};
	const onToggleResources = () => {
		setVariant(baseVariant === RESOURCES_OPEN ? PHONE_OPEN : RESOURCES_OPEN);
	};
	const onToggleInvestment = () => {
		setVariant(baseVariant === INVESTMENT_OPEN ? PHONE_OPEN : INVESTMENT_OPEN);
	};
	const accordionTransition = {
		duration: 0.38,
		ease: [0.22, 1, 0.36, 1],
	};
	const menuPanelTransition = {
		duration: 0.45,
		ease: [0.22, 1, 0.36, 1],
	};
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["YmfvgTG50", "tpyWFivQj", "DRm9pRmsR"].includes(baseVariant))
			return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "zvqvmgi_X") return false;
		return true;
	};
	const ref1 = React.useRef(null);
	const ref2 = React.useRef(null);
	const ref3 = React.useRef(null);
	const ref4 = React.useRef(null);
	const isDisplayed2 = () => {
		if (baseVariant === "zvqvmgi_X") return true;
		return false;
	};
	const isDisplayed3 = () => {
		if (["YmfvgTG50", "tpyWFivQj", "DRm9pRmsR"].includes(baseVariant))
			return true;
		return false;
	};
	const isDisplayed4 = () => {
		return false;
	};
	const isDisplayed5 = () => {
		return false;
	};
	const isDisplayed6 = () => {
		if (["YmfvgTG50", "tpyWFivQj", "DRm9pRmsR"].includes(baseVariant))
			return true;
		return false;
	};
	const isDisplayedResourceYears = () => {
		if (baseVariant === "tpyWFivQj") return true;
		return false;
	};
	const isDisplayedInvestmentYears = () => {
		if (baseVariant === "DRm9pRmsR") return true;
		return false;
	};
	const resourceYears = [
		{
			href: "https://drive.google.com/file/d/19J1KoeexWjVbiLdAM72OrNLhI0TA9BMj/view",
			label: "F.Y. 2026-27",
			nodeId: "mobileResourceFy202627",
		},
		{
			href: "https://drive.google.com/file/d/166KwytmjuKyKRITao_qaMeX7CXoKeXdS/view",
			label: "F.Y. 2025-26",
			nodeId: "mobileResourceFy202526",
		},
	];
	const investmentAdvisoryYears = [
		{
			href: "https://drive.google.com/file/d/19J1KoeexWjVbiLdAM72OrNLhI0TA9BMj/view",
			label: "F.Y. 2026-27",
			nodeId: "mobileFy202627",
		},
		{
			href: "https://drive.google.com/file/d/166KwytmjuKyKRITao_qaMeX7CXoKeXdS/view",
			label: "F.Y. 2025-26",
			nodeId: "mobileFy202526",
		},
		{
			href: "https://drive.google.com/file/d/1LVpDq5Bu-imaXSDRpNA8D9VhW4GKLydL/view",
			label: "F.Y. 2024-25",
			nodeId: "mobileFy202425",
		},
		{
			href: "https://drive.google.com/file/d/1oGJQr7K_ty04J2-zEuItcKQlqBWzI96R/view",
			label: "F.Y. 2023-24",
			nodeId: "mobileFy202324",
		},
	];
	const isMobileMenuOpen = ["YmfvgTG50", "tpyWFivQj", "DRm9pRmsR"].includes(
		baseVariant,
	);
	React.useEffect(() => {
		if (!isMobileMenuOpen) return;
		const previousOverflow = document.body.style.overflow;
		document.body.style.overflow = "hidden";
		return () => {
			document.body.style.overflow = previousOverflow;
		};
	}, [isMobileMenuOpen]);
	React.useEffect(() => {
		if (!["tpyWFivQj", "DRm9pRmsR"].includes(baseVariant)) return;
		const wrap = document.querySelector(
			baseVariant === "tpyWFivQj"
				? ".framer-e9rxN .framer-mobile-resource-years-wrap"
				: ".framer-e9rxN .framer-mobile-investment-years-wrap",
		);
		if (!wrap) return;
		const timer = window.setTimeout(() => {
			wrap.scrollIntoView({ behavior: "smooth", block: "nearest" });
		}, 80);
		return () => window.clearTimeout(timer);
	}, [baseVariant]);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-dxvjkb",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"hUMCu1JaQ"}
						ref={refBinding}
						// layout transforms break position:fixed and pull the bar / dropdowns up
						layout={baseVariant !== "hUMCu1JaQ"}
						transition={menuPanelTransition}
						style={{
							backgroundColor: "rgb(23, 35, 30)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								DRm9pRmsR: {
									"data-framer-name": "Variant 6",
								},
								tpyWFivQj: {
									"data-framer-name": "Variant 5",
								},
								YmfvgTG50: {
									"data-framer-name": "Phone Open",
								},
								zvqvmgi_X: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<AnimatePresence initial={false}>
							{isDisplayed() && (
							<motion.div
								key={"nav-main-bar"}
								className={"framer-104j7s6"}
								layoutDependency={layoutDependency}
								layoutId={"l3ZhV99zm"}
								initial={{ opacity: 0 }}
								animate={{ opacity: 1 }}
								exit={{ opacity: 0 }}
								transition={{ duration: 0.2, ease: "easeOut" }}
							>
								{isDisplayed1() && (
									<Link
										href={{
											webPageId: "augiA20Il",
										}}
										motionChild={true}
										nodeId={"TyWuTRWo8"}
										openInNewTab={false}
										scopeId={"dZbRlifrz"}
									>
										<Image1
											as={"a"}
											background={{
												alt: "",
												fit: "fit",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(28 +
															((componentViewport?.height || 94) -
																56 -
																((componentViewport?.height || 94) - 56) * 1) /
																2) +
														(0 +
															(((componentViewport?.height || 94) - 56) * 1 -
																0 -
																38) /
																2),
												),
												pixelHeight: 152,
												pixelWidth: 608,
												positionX: "center",
												positionY: "center",
												sizes: "152px",
												src: "/71j9VPXZ2Y7S8poJeoVhfLu8Mg0.png",
												srcSet:
													"/71j9VPXZ2Y7S8poJeoVhfLu8Mg0.png",
											}}
											className={"framer-rfjk13 framer-1gg1qt8"}
											data-framer-name={"Frame 7"}
											layoutDependency={layoutDependency}
											layoutId={"TyWuTRWo8"}
										/>
									</Link>
								)}
								{isDisplayed1() && (
									<motion.div
										className={"framer-9jcwas"}
										data-framer-name={"Frame 1236"}
										layoutDependency={layoutDependency}
										layoutId={"AUHyFZlUC"}
									>
										<Overlay
											blockDocumentScrolling={false}
											dismissWithEsc={false}
										>
											{(overlay) => (
												<_Fragment>
													<motion.div
														className={"framer-yjujj"}
														data-framer-name={"Frame 1318"}
														data-highlight={true}
														id={`${layoutId}-yjujj`}
														layoutDependency={layoutDependency}
														layoutId={"bwTZXzq5f"}
														onTap={onTap13elrgn({
															overlay,
														})}
														ref={ref1}
													>
														<RichText
															__fromCanvasComponent={true}
															className={"framer-i5nn1d"}
															data-framer-name={"Resources"}
															fonts={["FS;Satoshi-medium"]}
															layoutDependency={layoutDependency}
															layoutId={"YVDlID3AS"}
															style={{
																"--extracted-r6o4lv": "rgb(255, 255, 255)",
																"--framer-paragraph-spacing": "0px",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React.Fragment>
																<motion.p
																	style={{
																		"--font-selector":
																			"RlM7U2F0b3NoaS1tZWRpdW0=",
																		"--framer-font-family":
																			'"Satoshi", "Satoshi Placeholder", sans-serif',
																		"--framer-font-weight": "500",
																		"--framer-line-height": "120%",
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, rgb(255, 255, 255))",
																	}}
																>
																	{"Resources"}
																</motion.p>
															</React.Fragment>
														</RichText>
														<motion.div
															className={"framer-1ljm2w0"}
															data-framer-name={"Frame 1318"}
															layoutDependency={layoutDependency}
															layoutId={"VJIK_nYdO"}
														>
															<motion.div
																className={"framer-1oshhpf"}
																data-framer-name={"chevron-down"}
																layoutDependency={layoutDependency}
																layoutId={"RNPIt_gXW"}
															>
																<SVG
																	className={"framer-aufj54"}
																	data-framer-name={"Icon"}
																	fill={"rgba(0,0,0,1)"}
																	intrinsicHeight={8}
																	intrinsicWidth={14}
																	layoutDependency={layoutDependency}
																	layoutId={"jYxI8HP7x"}
																	svg={
																		'<svg width="14" height="8" viewBox="-1 -1 14 8" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M0.96967 0.21967C1.26256 -0.0732233 1.73744 -0.0732233 2.03033 0.21967L6 4.18934L9.96967 0.21967C10.2626 -0.0732233 10.7374 -0.0732233 11.0303 0.21967C11.3232 0.512563 11.3232 0.987437 11.0303 1.28033L6.53033 5.78033C6.23744 6.07322 5.76256 6.07322 5.46967 5.78033L0.96967 1.28033C0.676777 0.987437 0.676777 0.512563 0.96967 0.21967Z" fill="white"/>\n</svg>\n'
																	}
																	withExternalLayout={true}
																/>
															</motion.div>
														</motion.div>
														<AnimatePresence>
															{overlay.visible && (
																<Floating
																	alignment={"center"}
																	anchorRef={ref1}
																	className={cx(scopingClassNames, classNames)}
																	collisionDetection={true}
																	collisionDetectionPadding={20}
																	data-framer-portal-id={`${layoutId}-yjujj`}
																	offsetX={50}
																	offsetY={10}
																	onDismiss={overlay.hide}
																	placement={"bottom"}
																	safeArea={true}
																	zIndex={120}
																>
																	<MotionDivWithFX
																		__perspectiveFX={false}
																		__smartComponentFX={true}
																		__targetOpacity={1}
																		animate={animation1}
																		className={"framer-4i2xg1"}
																		exit={animation}
																		initial={animation2}
																		layoutDependency={layoutDependency}
																		layoutId={"s36yfOpdC"}
																		ref={ref2}
																		role={"dialog"}
																		style={{
																			backgroundColor: "rgb(255, 255, 255)",
																			borderBottomLeftRadius: 10,
																			borderBottomRightRadius: 10,
																			borderTopLeftRadius: 10,
																			borderTopRightRadius: 10,
																			boxShadow:
																				"0px 10px 20px 0px rgba(0, 0, 0, 0.05)",
																		}}
																	>
																		<motion.div
																			className={"framer-ke2ts3"}
																			data-framer-name={"Resources"}
																			layoutDependency={layoutDependency}
																			layoutId={"FotJ4mwjK"}
																			style={{
																				backgroundColor: "rgb(245, 242, 235)",
																				borderBottomLeftRadius: 12,
																				borderBottomRightRadius: 12,
																				borderTopLeftRadius: 12,
																				borderTopRightRadius: 12,
																				boxShadow:
																					"0px 1px 20px 0px rgba(0, 0, 0, 0.13)",
																			}}
																		>
																			<Link
																				href={{
																					webPageId: "F7srAjv5G",
																				}}
																				motionChild={true}
																				nodeId={"GOUqMxcoz"}
																				openInNewTab={false}
																				scopeId={"dZbRlifrz"}
																			>
																				<motion.a
																					className={
																						"framer-sv2c8z framer-1gg1qt8"
																					}
																					data-border={true}
																					data-framer-name={"Frame 1430105596"}
																					layoutDependency={layoutDependency}
																					layoutId={"GOUqMxcoz"}
																					style={{
																						"--border-bottom-width": "1px",
																						"--border-color":
																							"rgba(23, 35, 30, 0.12)",
																						"--border-left-width": "0px",
																						"--border-right-width": "0px",
																						"--border-style": "solid",
																						"--border-top-width": "0px",
																					}}
																				>
																					<RichText
																						__fromCanvasComponent={true}
																						className={"framer-8uiuj"}
																						data-framer-name={
																							"Meet the manager"
																						}
																						fonts={["FS;Satoshi-medium"]}
																						layoutDependency={layoutDependency}
																						layoutId={"JgCL3xqXr"}
																						style={{
																							"--extracted-r6o4lv":
																								"rgba(23, 35, 30, 0.6)",
																							"--framer-paragraph-spacing":
																								"0px",
																						}}
																						verticalAlignment={"top"}
																						withExternalLayout={true}
																					>
																						<React.Fragment>
																							<motion.p
																								style={{
																									"--font-selector":
																										"RlM7U2F0b3NoaS1tZWRpdW0=",
																									"--framer-font-family":
																										'"Satoshi", "Satoshi Placeholder", sans-serif',
																									"--framer-font-weight": "500",
																									"--framer-line-height":
																										"120%",
																									"--framer-text-color":
																										"var(--extracted-r6o4lv, rgba(23, 35, 30, 0.6))",
																								}}
																							>
																								{"Blogs"}
																							</motion.p>
																						</React.Fragment>
																					</RichText>
																				</motion.a>
																			</Link>
																			<Link
																				href={{
																					webPageId: "eeeMK_hWM",
																				}}
																				motionChild={true}
																				nodeId={"ztp1okACN"}
																				scopeId={"dZbRlifrz"}
																			>
																				<motion.a
																					className={
																						"framer-6rad1e framer-1gg1qt8"
																					}
																					data-border={true}
																					data-framer-name={"Frame 1430105596"}
																					layoutDependency={layoutDependency}
																					layoutId={"ztp1okACN"}
																					style={{
																						"--border-bottom-width": "1px",
																						"--border-color":
																							"rgba(23, 35, 30, 0.12)",
																						"--border-left-width": "0px",
																						"--border-right-width": "0px",
																						"--border-style": "solid",
																						"--border-top-width": "0px",
																					}}
																				>
																					<RichText
																						__fromCanvasComponent={true}
																						className={"framer-gsrm3w"}
																						data-framer-name={
																							"Meet the manager"
																						}
																						fonts={["FS;Satoshi-medium"]}
																						layoutDependency={layoutDependency}
																						layoutId={"B2traTY5L"}
																						style={{
																							"--extracted-r6o4lv":
																								"rgba(23, 35, 30, 0.6)",
																							"--framer-paragraph-spacing":
																								"0px",
																						}}
																						verticalAlignment={"top"}
																						withExternalLayout={true}
																					>
																						<React.Fragment>
																							<motion.p
																								style={{
																									"--font-selector":
																										"RlM7U2F0b3NoaS1tZWRpdW0=",
																									"--framer-font-family":
																										'"Satoshi", "Satoshi Placeholder", sans-serif',
																									"--framer-font-weight": "500",
																									"--framer-line-height":
																										"120%",
																									"--framer-text-color":
																										"var(--extracted-r6o4lv, rgba(23, 35, 30, 0.6))",
																								}}
																							>
																								{"Meet the manager"}
																							</motion.p>
																						</React.Fragment>
																					</RichText>
																				</motion.a>
																			</Link>
																			<Link
																				href={{
																					webPageId: "zDs7Sig2r",
																				}}
																				motionChild={true}
																				nodeId={"jljm0a3aI"}
																				scopeId={"dZbRlifrz"}
																			>
																				<motion.a
																					className={
																						"framer-1n3q7ho framer-1gg1qt8"
																					}
																					data-framer-name={"Frame 1430105597"}
																					layoutDependency={layoutDependency}
																					layoutId={"jljm0a3aI"}
																				>
																					<RichText
																						__fromCanvasComponent={true}
																						className={"framer-1mjsq12"}
																						data-framer-name={
																							"Coffee pe compounding"
																						}
																						fonts={["FS;Satoshi-medium"]}
																						layoutDependency={layoutDependency}
																						layoutId={"I3QTH1Vk3"}
																						style={{
																							"--extracted-r6o4lv":
																								"rgba(23, 35, 30, 0.6)",
																							"--framer-paragraph-spacing":
																								"0px",
																						}}
																						verticalAlignment={"top"}
																						withExternalLayout={true}
																					>
																						<React.Fragment>
																							<motion.p
																								style={{
																									"--font-selector":
																										"RlM7U2F0b3NoaS1tZWRpdW0=",
																									"--framer-font-family":
																										'"Satoshi", "Satoshi Placeholder", sans-serif',
																									"--framer-font-weight": "500",
																									"--framer-line-height":
																										"120%",
																									"--framer-text-color":
																										"var(--extracted-r6o4lv, rgba(23, 35, 30, 0.6))",
																								}}
																							>
																								{"Coffee pe compounding"}
																							</motion.p>
																						</React.Fragment>
																					</RichText>
																				</motion.a>
																			</Link>
																		</motion.div>
																	</MotionDivWithFX>
																</Floating>
															)}
														</AnimatePresence>
													</motion.div>
												</_Fragment>
											)}
										</Overlay>
										<motion.div
											className={"framer-1alxw4c"}
											data-framer-name={"Frame 1232"}
											layoutDependency={layoutDependency}
											layoutId={"mNIxo0OIN"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1cpjlkc"}
												data-framer-name={"About"}
												fonts={["FS;Satoshi-medium"]}
												layoutDependency={layoutDependency}
												layoutId={"gTU1l8iLk"}
												style={{
													"--extracted-r6o4lv": "rgb(255, 255, 255)",
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
															"--framer-font-family":
																'"Satoshi", "Satoshi Placeholder", sans-serif',
															"--framer-font-weight": "500",
															"--framer-line-height": "120%",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(255, 255, 255))",
														}}
													>
														<Link
															href={{
																webPageId: "brtedVB3g",
															}}
															motionChild={true}
															nodeId={"gTU1l8iLk"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"dZbRlifrz"}
															smoothScroll={false}
														>
															<motion.a
																className={"framer-styles-preset-jc6s9o"}
																data-styles-preset={"RPI55sIY7"}
															>
																{"About"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
										<Overlay
											blockDocumentScrolling={false}
											dismissWithEsc={false}
										>
											{(overlay1) => (
												<_Fragment>
													<motion.div
														className={"framer-1vwnn60"}
														data-framer-name={"Frame 1235"}
														data-highlight={true}
														id={`${layoutId}-1vwnn60`}
														layoutDependency={layoutDependency}
														layoutId={"WHpNx0MKy"}
														onMouseEnter={onMouseEnter13elrgn({
															overlay: overlay1,
														})}
														ref={ref3}
													>
														<RichText
															__fromCanvasComponent={true}
															className={"framer-3nu3xm"}
															data-framer-name={"Investment Advisory"}
															fonts={["FS;Satoshi-medium"]}
															layoutDependency={layoutDependency}
															layoutId={"pumkqmIHs"}
															style={{
																"--extracted-r6o4lv": "rgb(255, 255, 255)",
																"--framer-paragraph-spacing": "0px",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React.Fragment>
																<motion.p
																	style={{
																		"--font-selector":
																			"RlM7U2F0b3NoaS1tZWRpdW0=",
																		"--framer-font-family":
																			'"Satoshi", "Satoshi Placeholder", sans-serif',
																		"--framer-font-weight": "500",
																		"--framer-line-height": "120%",
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, rgb(255, 255, 255))",
																	}}
																>
																	{"Investment Advisory"}
																</motion.p>
															</React.Fragment>
														</RichText>
														<motion.div
															className={"framer-17ueag"}
															data-framer-name={"chevron-down"}
															layoutDependency={layoutDependency}
															layoutId={"R2FSQpw2T"}
														>
															<SVG
																className={"framer-156n5mf"}
																data-framer-name={"Icon"}
																layout={"position"}
																layoutDependency={layoutDependency}
																layoutId={"QEd9ppB9c"}
																opacity={1}
																svg={
																	'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 14 8"><path d="M 1.97 1.22 C 2.263 0.927 2.737 0.927 3.03 1.22 L 7 5.189 L 10.97 1.22 C 11.263 0.927 11.737 0.927 12.03 1.22 C 12.323 1.513 12.323 1.987 12.03 2.28 L 7.53 6.78 C 7.237 7.073 6.763 7.073 6.47 6.78 L 1.97 2.28 C 1.677 1.987 1.677 1.513 1.97 1.22 Z" fill="rgb(255,255,255)"></path></svg>'
																}
																svgContentId={9293151201}
																withExternalLayout={true}
															/>
														</motion.div>
														<AnimatePresence>
															{overlay1.visible && (
																<Floating
																	alignment={"center"}
																	anchorRef={ref3}
																	className={cx(scopingClassNames, classNames)}
																	collisionDetection={true}
																	collisionDetectionPadding={20}
																	data-framer-portal-id={`${layoutId}-1vwnn60`}
																	offsetX={0}
																	offsetY={10}
																	onDismiss={overlay1.hide}
																	placement={"bottom"}
																	safeArea={false}
																	zIndex={120}
																>
																	<MotionDivWithFX
																		__perspectiveFX={false}
																		__smartComponentFX={true}
																		__targetOpacity={1}
																		animate={animation1}
																		className={"framer-u91032"}
																		exit={animation}
																		initial={animation2}
																		layoutDependency={layoutDependency}
																		layoutId={"c7rbDqqgu"}
																		ref={ref4}
																		role={"dialog"}
																		style={{
																			backgroundColor: "rgb(255, 255, 255)",
																			borderBottomLeftRadius: 10,
																			borderBottomRightRadius: 10,
																			borderTopLeftRadius: 10,
																			borderTopRightRadius: 10,
																			boxShadow:
																				"0px 10px 20px 0px rgba(0, 0, 0, 0.05)",
																		}}
																	>
																		<motion.div
																			className={"framer-1athycy"}
																			data-framer-name={"Resources"}
																			layoutDependency={layoutDependency}
																			layoutId={"mtAFTbvtt"}
																			style={{
																				backgroundColor: "rgb(245, 242, 235)",
																				borderBottomLeftRadius: 12,
																				borderBottomRightRadius: 12,
																				borderTopLeftRadius: 12,
																				borderTopRightRadius: 12,
																				boxShadow:
																					"0px 1px 20px 0px rgba(0, 0, 0, 0.13)",
																			}}
																		>
																			{[
																				{
																					href: "https://drive.google.com/file/d/19J1KoeexWjVbiLdAM72OrNLhI0TA9BMj/view",
																					label: "F.Y. 2026-27",
																					nodeId: "TWcgSBdM_",
																					layoutId: "Mj0wFeIh0",
																					isLast: false,
																				},
																				{
																					href: "https://drive.google.com/file/d/166KwytmjuKyKRITao_qaMeX7CXoKeXdS/view",
																					label: "F.Y. 2025-26",
																					nodeId: "d9SID26ck",
																					layoutId: "nFHE_rlp3",
																					isLast: false,
																				},
																				{
																					href: "https://drive.google.com/file/d/1LVpDq5Bu-imaXSDRpNA8D9VhW4GKLydL/view",
																					label: "F.Y. 2024-25",
																					nodeId: "fy202425",
																					layoutId: "fy202425Label",
																					isLast: false,
																				},
																				{
																					href: "https://drive.google.com/file/d/1oGJQr7K_ty04J2-zEuItcKQlqBWzI96R/view",
																					label: "F.Y. 2023-24",
																					nodeId: "fy202324",
																					layoutId: "fy202324Label",
																					isLast: true,
																				},
																			].map((item) => (
																				<Link
																					key={item.nodeId}
																					href={item.href}
																					motionChild={true}
																					nodeId={item.nodeId}
																					openInNewTab={true}
																					scopeId={"dZbRlifrz"}
																				>
																					<motion.a
																						className={
																							item.isLast
																								? "framer-143prhv framer-1gg1qt8"
																								: "framer-1hhjg3e framer-1gg1qt8"
																						}
																						data-border={!item.isLast ? true : undefined}
																						data-framer-name={"Frame 1430105596"}
																						layoutDependency={layoutDependency}
																						layoutId={item.nodeId}
																						style={
																							item.isLast
																								? undefined
																								: {
																										"--border-bottom-width": "1px",
																										"--border-color":
																											"rgba(23, 35, 30, 0.12)",
																										"--border-left-width": "0px",
																										"--border-right-width": "0px",
																										"--border-style": "solid",
																										"--border-top-width": "0px",
																									}
																						}
																					>
																						<RichText
																							__fromCanvasComponent={true}
																							className={
																								item.isLast
																									? "framer-c5zyey"
																									: "framer-aph66g"
																							}
																							data-framer-name={item.label}
																							fonts={["FS;Satoshi-medium"]}
																							layoutDependency={layoutDependency}
																							layoutId={item.layoutId}
																							style={{
																								"--extracted-r6o4lv":
																									"rgba(23, 35, 30, 0.6)",
																								"--framer-paragraph-spacing":
																									"0px",
																							}}
																							verticalAlignment={"top"}
																							withExternalLayout={true}
																						>
																							<React.Fragment>
																								<motion.p
																									style={{
																										"--font-selector":
																											"RlM7U2F0b3NoaS1tZWRpdW0=",
																										"--framer-font-family":
																											'"Satoshi", "Satoshi Placeholder", sans-serif',
																										"--framer-font-weight": "500",
																										"--framer-line-height":
																											"120%",
																										"--framer-text-color":
																											"var(--extracted-r6o4lv, rgba(23, 35, 30, 0.6))",
																									}}
																								>
																									{item.label}
																								</motion.p>
																							</React.Fragment>
																						</RichText>
																					</motion.a>
																				</Link>
																			))}
																		</motion.div>
																	</MotionDivWithFX>
																</Floating>
															)}
														</AnimatePresence>
													</motion.div>
												</_Fragment>
											)}
										</Overlay>
										<motion.div
											className={"framer-1b8uy6x"}
											data-framer-name={"Frame 1236"}
											layoutDependency={layoutDependency}
											layoutId={"SE9JgDT88"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-q8l0ae"}
												data-framer-name={"Contact"}
												fonts={["FS;Satoshi-medium"]}
												layoutDependency={layoutDependency}
												layoutId={"eBnBcv1qA"}
												style={{
													"--extracted-r6o4lv": "rgb(255, 255, 255)",
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
															"--framer-font-family":
																'"Satoshi", "Satoshi Placeholder", sans-serif',
															"--framer-font-weight": "500",
															"--framer-line-height": "120%",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(255, 255, 255))",
														}}
													>
														<Link
															href={{
																webPageId: "mighqlLao",
															}}
															motionChild={true}
															nodeId={"eBnBcv1qA"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"dZbRlifrz"}
															smoothScroll={false}
														>
															<motion.a
																className={"framer-styles-preset-jc6s9o"}
																data-styles-preset={"RPI55sIY7"}
															>
																{"Contact"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>
								)}
								{isDisplayed1() && (
									<motion.div
										className={"framer-kunebk"}
										layoutDependency={layoutDependency}
										layoutId={"ox2rASnTc"}
									>
										<Link
											href={"https://app.sapientwealth.net/app/#/login"}
											motionChild={true}
											nodeId={"nt_ZSY_TP"}
											scopeId={"dZbRlifrz"}
										>
											<motion.a
												className={"framer-lw0ywb framer-1gg1qt8"}
												data-framer-name={"Frame 1236"}
												layoutDependency={layoutDependency}
												layoutId={"nt_ZSY_TP"}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-r4rmg6"}
													data-framer-name={"Contact"}
													fonts={["FS;Satoshi-medium"]}
													layoutDependency={layoutDependency}
													layoutId={"VkHM7EmNt"}
													style={{
														"--extracted-r6o4lv": "rgb(255, 255, 255)",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
																"--framer-font-family":
																	'"Satoshi", "Satoshi Placeholder", sans-serif',
																"--framer-font-weight": "500",
																"--framer-line-height": "120%",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(255, 255, 255))",
															}}
														>
															{"Login"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.a>
										</Link>
										<Link
											href={{
												webPageId: "mighqlLao",
											}}
											motionChild={true}
											nodeId={"m3Rl6wVgT"}
											scopeId={"dZbRlifrz"}
										>
											<motion.a
												className={"framer-19u6pmc framer-1gg1qt8"}
												data-framer-name={"Frame 10"}
												layoutDependency={layoutDependency}
												layoutId={"m3Rl6wVgT"}
												style={{
													backgroundColor: "rgb(164, 207, 107)",
													borderBottomLeftRadius: 12,
													borderBottomRightRadius: 12,
													borderTopLeftRadius: 12,
													borderTopRightRadius: 12,
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-cd6bkk"}
													data-framer-name={"Get Started"}
													fonts={["FS;Satoshi-bold"]}
													layoutDependency={layoutDependency}
													layoutId={"kH5r9Siqz"}
													style={{
														"--extracted-r6o4lv": "rgb(23, 35, 30)",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "RlM7U2F0b3NoaS1ib2xk",
																"--framer-font-family":
																	'"Satoshi", "Satoshi Placeholder", sans-serif',
																"--framer-font-weight": "700",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(23, 35, 30))",
															}}
														>
															{"Get Started"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.a>
										</Link>
									</motion.div>
								)}
								{isDisplayed2() && (
									<Link
										href={{
											webPageId: "augiA20Il",
										}}
										motionChild={true}
										nodeId={"rAXpVLXe1"}
										scopeId={"dZbRlifrz"}
									>
										<Image1
											as={"a"}
											background={{
												alt: "",
												fit: "fit",
												pixelHeight: 80,
												pixelWidth: 320,
												positionX: "center",
												positionY: "center",
												src: "/Fgmuui8XlNgaggnZ03hnzOFHnUE.png",
											}}
											className={"framer-8om0te framer-1gg1qt8"}
											data-framer-name={"Frame 7"}
											layoutDependency={layoutDependency}
											layoutId={"rAXpVLXe1"}
											{...addPropertyOverrides(
												{
													zvqvmgi_X: {
														background: {
															alt: "",
															fit: "fit",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	(12 +
																		((componentViewport?.height || 54) -
																			24 -
																			((componentViewport?.height || 54) - 24) *
																				1) /
																			2) +
																	(0 +
																		(((componentViewport?.height || 54) - 24) *
																			1 -
																			0 -
																			(((componentViewport?.height || 54) -
																				24) *
																				1 -
																				0) *
																				1) /
																			2),
															),
															pixelHeight: 80,
															pixelWidth: 320,
															positionX: "center",
															positionY: "center",
															sizes: `calc(${(((componentViewport?.height || 54) - 24) * 1 - 0) * 1} * 4)`,
															src: "/Fgmuui8XlNgaggnZ03hnzOFHnUE.png",
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</Link>
								)}
								{isDisplayed2() && (
									<motion.div
										className={"framer-29s8zc"}
										data-framer-name={"Frame 1430105626"}
										layoutDependency={layoutDependency}
										layoutId={"HqAMljdIv"}
									>
										<Link
											href={{
												webPageId: "mighqlLao",
											}}
											motionChild={true}
											nodeId={"lS1VTwTJn"}
											scopeId={"dZbRlifrz"}
										>
											<motion.a
												className={"framer-15jnnan framer-1gg1qt8"}
												data-framer-name={"Frame 10"}
												layoutDependency={layoutDependency}
												layoutId={"lS1VTwTJn"}
												style={{
													backgroundColor: "rgb(164, 207, 107)",
													borderBottomLeftRadius: 6,
													borderBottomRightRadius: 6,
													borderTopLeftRadius: 6,
													borderTopRightRadius: 6,
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-1wrwvlu"}
													data-framer-name={"Get Started"}
													fonts={["FS;Satoshi-bold"]}
													layoutDependency={layoutDependency}
													layoutId={"ZH_GrWlKc"}
													style={{
														"--extracted-r6o4lv": "rgb(23, 35, 30)",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "RlM7U2F0b3NoaS1ib2xk",
																"--framer-font-family":
																	'"Satoshi", "Satoshi Placeholder", sans-serif',
																"--framer-font-size": "12px",
																"--framer-font-weight": "700",
																"--framer-letter-spacing": "-0.01em",
																"--framer-line-height": "120%",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(23, 35, 30))",
															}}
														>
															{"Get Started"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.a>
										</Link>
										<motion.div
											className={"framer-qfpb8"}
											data-highlight={true}
											layoutDependency={layoutDependency}
											layoutId={"AKS6fDA3r"}
											onClick={onTapnx26yq}
											onTap={onTapnx26yq}
											role={"button"}
											tabIndex={0}
											onKeyDown={(e) => {
												if (e.key === "Enter" || e.key === " ") {
													e.preventDefault();
													onTapnx26yq();
												}
											}}
										>
											<motion.div
												className={"framer-16bijsw"}
												data-framer-name={"Top"}
												layoutDependency={layoutDependency}
												layoutId={"DD7h9rc3m"}
												style={{
													backgroundColor: "rgb(255, 255, 255)",
													borderBottomLeftRadius: 10,
													borderBottomRightRadius: 10,
													borderTopLeftRadius: 10,
													borderTopRightRadius: 10,
												}}
												whileTap={{ scaleX: 0.85 }}
												transition={{ duration: 0.2 }}
											/>
											<motion.div
												className={"framer-1qz0zq7"}
												data-framer-name={"Top"}
												layoutDependency={layoutDependency}
												layoutId={"zylshq_lx"}
												style={{
													backgroundColor: "rgb(255, 255, 255)",
													borderBottomLeftRadius: 10,
													borderBottomRightRadius: 10,
													borderTopLeftRadius: 10,
													borderTopRightRadius: 10,
												}}
												whileTap={{ opacity: 0 }}
												transition={{ duration: 0.15 }}
											/>
											<motion.div
												className={"framer-1sxtqv7"}
												data-framer-name={"Top"}
												layoutDependency={layoutDependency}
												layoutId={"Qz219curP"}
												style={{
													backgroundColor: "rgb(255, 255, 255)",
													borderBottomLeftRadius: 10,
													borderBottomRightRadius: 10,
													borderTopLeftRadius: 10,
													borderTopRightRadius: 10,
												}}
												whileTap={{ scaleX: 0.85 }}
												transition={{ duration: 0.2 }}
											/>
										</motion.div>
									</motion.div>
								)}
							</motion.div>
							)}
						</AnimatePresence>
						<AnimatePresence initial={false}>
							{isMobileMenuOpen ? (
								<motion.div
									key={"mobile-open-panel"}
									className={"framer-mobile-open-panel"}
									initial={{ opacity: 0, height: 0 }}
									animate={{ opacity: 1, height: "auto" }}
									exit={{ opacity: 0, height: 0 }}
									transition={menuPanelTransition}
									style={{
										display: "flex",
										flexDirection: "column",
										gap: 12,
										overflow: "hidden",
										width: "100%",
									}}
								>
							<motion.div
								className={"framer-ljlhhe"}
								layoutDependency={layoutDependency}
								layoutId={"TP6OnVjby"}
							>
								<Link
									motionChild={true}
									nodeId={"Tyqx2Q0uF"}
									scopeId={"dZbRlifrz"}
									{...addPropertyOverrides(
										{
											DRm9pRmsR: {
												href: {
													webPageId: "augiA20Il",
												},
											},
											tpyWFivQj: {
												href: {
													webPageId: "augiA20Il",
												},
											},
											YmfvgTG50: {
												href: {
													webPageId: "augiA20Il",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<Image1
										background={{
											alt: "",
											fit: "fit",
											pixelHeight: 80,
											pixelWidth: 320,
											positionX: "center",
											positionY: "center",
											src: "/Fgmuui8XlNgaggnZ03hnzOFHnUE.png",
										}}
										className={"framer-5pij6m framer-1gg1qt8"}
										data-framer-name={"Frame 7"}
										layoutDependency={layoutDependency}
										layoutId={"Tyqx2Q0uF"}
										{...addPropertyOverrides(
											{
												DRm9pRmsR: {
													as: "a",
													background: {
														alt: "",
														fit: "fit",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) + 12 + 0 + 0,
														),
														pixelHeight: 80,
														pixelWidth: 320,
														positionX: "center",
														positionY: "center",
														sizes: "120px",
														src: "/Fgmuui8XlNgaggnZ03hnzOFHnUE.png",
													},
												},
												tpyWFivQj: {
													as: "a",
													background: {
														alt: "",
														fit: "fit",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) + 12 + 0 + 0,
														),
														pixelHeight: 80,
														pixelWidth: 320,
														positionX: "center",
														positionY: "center",
														sizes: "120px",
														src: "/Fgmuui8XlNgaggnZ03hnzOFHnUE.png",
													},
												},
												YmfvgTG50: {
													as: "a",
													background: {
														alt: "",
														fit: "fit",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) + 12 + 0 + 0,
														),
														pixelHeight: 80,
														pixelWidth: 320,
														positionX: "center",
														positionY: "center",
														sizes: "120px",
														src: "/Fgmuui8XlNgaggnZ03hnzOFHnUE.png",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</Link>
								<motion.div
									className={"framer-5vzw3d"}
									data-framer-name={"Frame 1430105626"}
									layoutDependency={layoutDependency}
									layoutId={"oZY6b0aze"}
								>
									<motion.div
										className={"framer-eylbnf"}
										data-highlight={true}
										layoutDependency={layoutDependency}
										layoutId={"khhS16HPN"}
										onClick={onTap1x5cmto}
										onTap={onTap1x5cmto}
										role={"button"}
										tabIndex={0}
										onKeyDown={(e) => {
											if (e.key === "Enter" || e.key === " ") {
												e.preventDefault();
												onTap1x5cmto();
											}
										}}
									>
										<motion.div
											className={"framer-zfyxe1"}
											data-framer-name={"Top"}
											layoutDependency={layoutDependency}
											layoutId={"OKXuY0eFY"}
											initial={{ rotate: 0, opacity: 0 }}
											animate={{ rotate: 45, opacity: 1 }}
											transition={menuPanelTransition}
											style={{
												backgroundColor: "rgb(255, 255, 255)",
												borderBottomLeftRadius: 10,
												borderBottomRightRadius: 10,
												borderTopLeftRadius: 10,
												borderTopRightRadius: 10,
											}}
										/>
										<motion.div
											className={"framer-1h6gvk4"}
											data-framer-name={"Top"}
											layoutDependency={layoutDependency}
											layoutId={"h2E5r4e2M"}
											initial={{ rotate: 0, opacity: 0 }}
											animate={{ rotate: -45, opacity: 1 }}
											transition={menuPanelTransition}
											style={{
												backgroundColor: "rgb(255, 255, 255)",
												borderBottomLeftRadius: 10,
												borderBottomRightRadius: 10,
												borderTopLeftRadius: 10,
												borderTopRightRadius: 10,
											}}
										/>
									</motion.div>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-9nd0i6"}
								data-framer-name={"Links"}
								layoutDependency={layoutDependency}
								layoutId={"pMNvWIuRC"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1123vbo"}
									fonts={["FS;Satoshi-regular"]}
									layoutDependency={layoutDependency}
									layoutId={"lV08NCHtP"}
									style={{
										"--extracted-r6o4lv": "rgb(255, 255, 255)",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									data-highlight={true}
									role={"button"}
									tabIndex={0}
									onClick={onToggleResources}
									onTap={onToggleResources}
									onKeyDown={(e) => {
										if (e.key === "Enter" || e.key === " ") {
											e.preventDefault();
											onToggleResources();
										}
									}}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--font-selector": "RlM7U2F0b3NoaS1yZWd1bGFy",
												"--framer-font-family":
													'"Satoshi", "Satoshi Placeholder", sans-serif',
												"--framer-font-size": "24px",
												"--framer-line-height": "1.5em",
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgb(255, 255, 255))",
											}}
										>
											<motion.span
												data-text-fill={"true"}
												style={{
													backgroundImage:
														"linear-gradient(0deg, rgb(255, 255, 255) 0%, rgb(255, 255, 255) 100%)",
												}}
											>
												{"Resources"}
											</motion.span>
										</motion.p>
									</React.Fragment>
								</RichText>
								{isDisplayed4() && (
									<Link
										href={{
											webPageId: "eeeMK_hWM",
										}}
										motionChild={true}
										nodeId={"mOQrSlfoG"}
										scopeId={"dZbRlifrz"}
									>
										<motion.a
											className={"framer-6zyxr8 framer-1gg1qt8"}
											layoutDependency={layoutDependency}
											layoutId={"mOQrSlfoG"}
										>
											{isDisplayed4() && (
												<RichText
													__fromCanvasComponent={true}
													className={"framer-1wuie2q"}
													fonts={["FS;Satoshi-regular"]}
													layoutDependency={layoutDependency}
													layoutId={"QMjB_h3Vg"}
													style={{
														"--extracted-r6o4lv": "rgb(255, 255, 255)",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "RlM7U2F0b3NoaS1yZWd1bGFy",
																"--framer-font-family":
																	'"Satoshi", "Satoshi Placeholder", sans-serif',
																"--framer-font-size": "20px",
																"--framer-line-height": "1.5em",
																"--framer-text-alignment": "left",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(255, 255, 255))",
															}}
														>
															<motion.span
																data-text-fill={"true"}
																style={{
																	backgroundImage:
																		"linear-gradient(0deg, rgb(255, 255, 255) 0%, rgb(255, 255, 255) 100%)",
																}}
															>
																{"Meet the manager"}
															</motion.span>
														</motion.p>
													</React.Fragment>
												</RichText>
											)}
										</motion.a>
									</Link>
								)}
								{isDisplayed5() && (
									<Link
										href={{
											webPageId: "zDs7Sig2r",
										}}
										motionChild={true}
										nodeId={"yNpZpB8yj"}
										scopeId={"dZbRlifrz"}
									>
										<motion.a
											className={"framer-b6p5t framer-1gg1qt8"}
											layoutDependency={layoutDependency}
											layoutId={"yNpZpB8yj"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-r0vdln"}
												fonts={["FS;Satoshi-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"XjnldkzcJ"}
												style={{
													"--extracted-r6o4lv": "rgb(255, 255, 255)",
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "RlM7U2F0b3NoaS1yZWd1bGFy",
															"--framer-font-family":
																'"Satoshi", "Satoshi Placeholder", sans-serif',
															"--framer-font-size": "20px",
															"--framer-line-height": "1.5em",
															"--framer-text-alignment": "left",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(255, 255, 255))",
														}}
													>
														<motion.span
															data-text-fill={"true"}
															style={{
																backgroundImage:
																	"linear-gradient(0deg, rgb(255, 255, 255) 0%, rgb(255, 255, 255) 100%)",
															}}
														>
															{"Coffee pe compounding"}
														</motion.span>
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.a>
									</Link>
								)}
								{isDisplayed4() && (
									<Link
										href={{
											webPageId: "F7srAjv5G",
										}}
										motionChild={true}
										nodeId={"R9kRxpQBK"}
										scopeId={"dZbRlifrz"}
									>
										<motion.a
											className={"framer-1cfrgd3 framer-1gg1qt8"}
											layoutDependency={layoutDependency}
											layoutId={"R9kRxpQBK"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1dn612f"}
												fonts={["FS;Satoshi-regular"]}
												layoutDependency={layoutDependency}
												layoutId={"wqS8uz2a6"}
												style={{
													"--extracted-r6o4lv": "rgb(255, 255, 255)",
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "RlM7U2F0b3NoaS1yZWd1bGFy",
															"--framer-font-family":
																'"Satoshi", "Satoshi Placeholder", sans-serif',
															"--framer-font-size": "20px",
															"--framer-line-height": "1.5em",
															"--framer-text-alignment": "left",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(255, 255, 255))",
														}}
													>
														<motion.span
															data-text-fill={"true"}
															style={{
																backgroundImage:
																	"linear-gradient(0deg, rgb(255, 255, 255) 0%, rgb(255, 255, 255) 100%)",
															}}
														>
															{"Blogs"}
														</motion.span>
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.a>
									</Link>
								)}
								<AnimatePresence initial={false} mode="sync">
									{isDisplayedResourceYears() && (
										<motion.div
											key={"mobile-resource-years"}
											className={"framer-mobile-resource-years-wrap"}
											initial={{ height: 0, opacity: 0 }}
											animate={{ height: "auto", opacity: 1 }}
											exit={{ height: 0, opacity: 0 }}
											transition={accordionTransition}
											style={{
												display: "flex",
												flexDirection: "column",
												gap: 8,
												overflow: "hidden",
												width: "100%",
											}}
										>
											{resourceYears.map((item, index) => (
												<Link
													key={item.nodeId}
													href={item.href}
													motionChild={true}
													nodeId={item.nodeId}
													openInNewTab={true}
													scopeId={"dZbRlifrz"}
												>
													<motion.a
														className={`framer-mobile-fy framer-mobile-resource-fy-${index} framer-1gg1qt8`}
														layoutDependency={layoutDependency}
														layoutId={item.nodeId}
														initial={{ opacity: 0, y: -6 }}
														animate={{ opacity: 1, y: 0 }}
														exit={{ opacity: 0, y: -4 }}
														transition={{
															...accordionTransition,
															delay: 0.04 * index,
														}}
													>
														<RichText
															__fromCanvasComponent={true}
															className={"framer-1dn612f"}
															fonts={["FS;Satoshi-regular"]}
															layoutDependency={layoutDependency}
															layoutId={`${item.nodeId}-label`}
															style={{
																"--extracted-r6o4lv": "rgb(255, 255, 255)",
																"--framer-paragraph-spacing": "0px",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React.Fragment>
																<motion.p
																	style={{
																		"--font-selector": "RlM7U2F0b3NoaS1yZWd1bGFy",
																		"--framer-font-family":
																			'"Satoshi", "Satoshi Placeholder", sans-serif',
																		"--framer-font-size": "20px",
																		"--framer-line-height": "1.5em",
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, rgb(255, 255, 255))",
																	}}
																>
																	<motion.span
																		data-text-fill={"true"}
																		style={{
																			backgroundImage:
																				"linear-gradient(0deg, rgb(255, 255, 255) 0%, rgb(255, 255, 255) 100%)",
																		}}
																	>
																		{item.label}
																	</motion.span>
																</motion.p>
															</React.Fragment>
														</RichText>
													</motion.a>
												</Link>
											))}
										</motion.div>
									)}
								</AnimatePresence>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-2cydrd"}
									fonts={["FS;Satoshi-regular"]}
									layoutDependency={layoutDependency}
									layoutId={"bIavqGbaN"}
									style={{
										"--extracted-r6o4lv": "rgb(255, 255, 255)",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--font-selector": "RlM7U2F0b3NoaS1yZWd1bGFy",
												"--framer-font-family":
													'"Satoshi", "Satoshi Placeholder", sans-serif',
												"--framer-font-size": "24px",
												"--framer-line-height": "1.5em",
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgb(255, 255, 255))",
											}}
										>
											<Link
												href={{
													webPageId: "brtedVB3g",
												}}
												motionChild={true}
												nodeId={"bIavqGbaN"}
												openInNewTab={false}
												relValues={[]}
												scopeId={"dZbRlifrz"}
												smoothScroll={false}
											>
												<motion.a
													className={"framer-styles-preset-jc6s9o"}
													data-styles-preset={"RPI55sIY7"}
												>
													{"About"}
												</motion.a>
											</Link>
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-5nf8yk"}
									fonts={["FS;Satoshi-regular"]}
									layoutDependency={layoutDependency}
									layoutId={"wxqxfEaHm"}
									style={{
										"--extracted-r6o4lv": "rgb(255, 255, 255)",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									data-highlight={true}
									role={"button"}
									tabIndex={0}
									onClick={onToggleInvestment}
									onTap={onToggleInvestment}
									onKeyDown={(e) => {
										if (e.key === "Enter" || e.key === " ") {
											e.preventDefault();
											onToggleInvestment();
										}
									}}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--font-selector": "RlM7U2F0b3NoaS1yZWd1bGFy",
												"--framer-font-family":
													'"Satoshi", "Satoshi Placeholder", sans-serif',
												"--framer-font-size": "24px",
												"--framer-line-height": "1.5em",
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgb(255, 255, 255))",
											}}
										>
											<motion.span
												data-text-fill={"true"}
												style={{
													backgroundImage:
														"radial-gradient(50% 50% at 50% 50%, rgb(255, 255, 255) 0%, rgb(255, 255, 255) 100%)",
												}}
											>
												{"Investment Advisory"}
											</motion.span>
										</motion.p>
									</React.Fragment>
								</RichText>
								<AnimatePresence initial={false} mode="sync">
									{isDisplayedInvestmentYears() && (
										<motion.div
											key={"mobile-investment-years"}
											className={"framer-mobile-investment-years-wrap"}
											initial={{ height: 0, opacity: 0 }}
											animate={{ height: "auto", opacity: 1 }}
											exit={{ height: 0, opacity: 0 }}
											transition={accordionTransition}
											style={{
												display: "flex",
												flexDirection: "column",
												gap: 8,
												overflow: "hidden",
												width: "100%",
											}}
										>
											{investmentAdvisoryYears.map((item, index) => (
												<Link
													key={item.nodeId}
													href={item.href}
													motionChild={true}
													nodeId={item.nodeId}
													openInNewTab={true}
													scopeId={"dZbRlifrz"}
												>
													<motion.a
														className={`framer-mobile-fy framer-mobile-fy-${index} framer-1gg1qt8`}
														layoutDependency={layoutDependency}
														layoutId={item.nodeId}
														initial={{ opacity: 0, y: -6 }}
														animate={{ opacity: 1, y: 0 }}
														exit={{ opacity: 0, y: -4 }}
														transition={{
															...accordionTransition,
															delay: 0.04 * index,
														}}
													>
														<RichText
															__fromCanvasComponent={true}
															className={"framer-1dn612f"}
															fonts={["FS;Satoshi-regular"]}
															layoutDependency={layoutDependency}
															layoutId={`${item.nodeId}-label`}
															style={{
																"--extracted-r6o4lv": "rgb(255, 255, 255)",
																"--framer-paragraph-spacing": "0px",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React.Fragment>
																<motion.p
																	style={{
																		"--font-selector": "RlM7U2F0b3NoaS1yZWd1bGFy",
																		"--framer-font-family":
																			'"Satoshi", "Satoshi Placeholder", sans-serif',
																		"--framer-font-size": "20px",
																		"--framer-line-height": "1.5em",
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, rgb(255, 255, 255))",
																	}}
																>
																	<motion.span
																		data-text-fill={"true"}
																		style={{
																			backgroundImage:
																				"linear-gradient(0deg, rgb(255, 255, 255) 0%, rgb(255, 255, 255) 100%)",
																		}}
																	>
																		{item.label}
																	</motion.span>
																</motion.p>
															</React.Fragment>
														</RichText>
													</motion.a>
												</Link>
											))}
										</motion.div>
									)}
								</AnimatePresence>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1umy14"}
									fonts={["FS;Satoshi-regular"]}
									layoutDependency={layoutDependency}
									layoutId={"I6eWwGgO5"}
									style={{
										"--extracted-r6o4lv": "rgb(255, 255, 255)",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--font-selector": "RlM7U2F0b3NoaS1yZWd1bGFy",
												"--framer-font-family":
													'"Satoshi", "Satoshi Placeholder", sans-serif',
												"--framer-font-size": "24px",
												"--framer-line-height": "1.5em",
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgb(255, 255, 255))",
											}}
										>
											<motion.span
												data-text-fill={"true"}
												style={{
													backgroundImage:
														"radial-gradient(50% 50% at 50% 50%, rgb(255, 255, 255) 0%, rgb(255, 255, 255) 100%)",
												}}
											>
												<Link
													href={{
														webPageId: "mighqlLao",
													}}
													motionChild={true}
													nodeId={"I6eWwGgO5"}
													openInNewTab={false}
													relValues={[]}
													scopeId={"dZbRlifrz"}
													smoothScroll={false}
												>
													<motion.a
														className={"framer-styles-preset-jc6s9o"}
														data-styles-preset={"RPI55sIY7"}
													>
														{"Contact"}
													</motion.a>
												</Link>
											</motion.span>
										</motion.p>
									</React.Fragment>
								</RichText>
								{isDisplayed6() && (
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1addgu7"}
										fonts={["FS;Satoshi-regular"]}
										layoutDependency={layoutDependency}
										layoutId={"eBvKE8eER"}
										style={{
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "RlM7U2F0b3NoaS1yZWd1bGFy",
													"--framer-font-family":
														'"Satoshi", "Satoshi Placeholder", sans-serif',
													"--framer-font-size": "24px",
													"--framer-line-height": "1.5em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(255, 255, 255))",
												}}
											>
												<motion.span
													data-text-fill={"true"}
													style={{
														backgroundImage:
															"radial-gradient(50% 50% at 50% 50%, rgb(255, 255, 255) 0%, rgb(255, 255, 255) 100%)",
													}}
												>
													<Link
														href={"https://app.sapientwealth.net/app/#/login"}
														motionChild={true}
														nodeId={"eBvKE8eER"}
														openInNewTab={true}
														relValues={[]}
														scopeId={"dZbRlifrz"}
														smoothScroll={false}
													>
														<motion.a
															className={"framer-styles-preset-jc6s9o"}
															data-styles-preset={"RPI55sIY7"}
														>
															{"Login"}
														</motion.a>
													</Link>
												</motion.span>
											</motion.p>
										</React.Fragment>
									</RichText>
								)}
							</motion.div>
							<Link
								motionChild={true}
								nodeId={"AFoxAwDhq"}
								scopeId={"dZbRlifrz"}
								{...addPropertyOverrides(
									{
										DRm9pRmsR: {
											href: {
												webPageId: "mighqlLao",
											},
										},
										tpyWFivQj: {
											href: {
												webPageId: "mighqlLao",
											},
										},
										YmfvgTG50: {
											href: {
												webPageId: "mighqlLao",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<motion.a
									className={"framer-k0hqrv framer-1gg1qt8"}
									data-framer-name={"Frame 10"}
									layoutDependency={layoutDependency}
									layoutId={"AFoxAwDhq"}
									style={{
										backgroundColor: "rgb(164, 207, 107)",
										borderBottomLeftRadius: 12,
										borderBottomRightRadius: 12,
										borderTopLeftRadius: 12,
										borderTopRightRadius: 12,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1xcjfd0"}
										data-framer-name={"Get Started"}
										fonts={["FS;Satoshi-bold"]}
										layoutDependency={layoutDependency}
										layoutId={"mzswsoGbc"}
										style={{
											"--extracted-r6o4lv": "rgb(23, 35, 30)",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "RlM7U2F0b3NoaS1ib2xk",
													"--framer-font-family":
														'"Satoshi", "Satoshi Placeholder", sans-serif',
													"--framer-font-weight": "700",
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(23, 35, 30))",
												}}
											>
												{"Get Started"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.a>
							</Link>
								</motion.div>
							) : null}
						</AnimatePresence>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-e9rxN.framer-1gg1qt8, .framer-e9rxN .framer-1gg1qt8 { display: block; }",
	".framer-e9rxN.framer-dxvjkb { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: 94px; justify-content: center; padding: 28px 24px 28px 24px; position: relative; width: 100%; max-width: 100%; }",
	".framer-e9rxN .framer-104j7s6 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: 100%; justify-content: space-between; max-width: 1200px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-e9rxN .framer-rfjk13 { flex: none; height: 38px; position: relative; text-decoration: none; width: 152px; }",
	".framer-e9rxN .framer-9jcwas { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-e9rxN .framer-yjujj { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-e9rxN .framer-i5nn1d, .framer-e9rxN .framer-8uiuj, .framer-e9rxN .framer-gsrm3w, .framer-e9rxN .framer-1mjsq12, .framer-e9rxN .framer-1cpjlkc, .framer-e9rxN .framer-3nu3xm, .framer-e9rxN .framer-aph66g, .framer-e9rxN .framer-c5zyey, .framer-e9rxN .framer-q8l0ae, .framer-e9rxN .framer-r4rmg6, .framer-e9rxN .framer-cd6bkk, .framer-e9rxN .framer-1wrwvlu, .framer-e9rxN .framer-1123vbo, .framer-e9rxN .framer-1wuie2q, .framer-e9rxN .framer-r0vdln, .framer-e9rxN .framer-1dn612f, .framer-e9rxN .framer-2cydrd, .framer-e9rxN .framer-5nf8yk, .framer-e9rxN .framer-1umy14, .framer-e9rxN .framer-1addgu7 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-e9rxN .framer-1ljm2w0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 4px 0px 0px 0px; position: relative; width: min-content; }",
	".framer-e9rxN .framer-1oshhpf { aspect-ratio: 1 / 1; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 18px); overflow: hidden; position: relative; width: 18px; }",
	".framer-e9rxN .framer-aufj54 { bottom: 7px; flex: none; left: 2px; position: absolute; right: 6px; top: 5px; }",
	".framer-e9rxN .framer-4i2xg1 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 150px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 200px; will-change: var(--framer-will-change-override, transform); }",
	".framer-e9rxN .framer-ke2ts3, .framer-e9rxN .framer-1athycy { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 8px 12px 8px 12px; position: relative; width: min-content; z-index: 1; }",
	".framer-e9rxN .framer-sv2c8z, .framer-e9rxN .framer-6rad1e, .framer-e9rxN .framer-1hhjg3e { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 8px 0px 12px 0px; position: relative; text-decoration: none; width: 100%; }",
	".framer-e9rxN .framer-1n3q7ho { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 2px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 12px 0px; position: relative; text-decoration: none; width: 100%; }",
	".framer-e9rxN .framer-1alxw4c, .framer-e9rxN .framer-1b8uy6x { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-e9rxN .framer-1vwnn60 { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-e9rxN .framer-17ueag { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: var(--framer-aspect-ratio-supported, 18px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 18px; }",
	".framer-e9rxN .framer-156n5mf { flex: none; height: 8px; position: relative; width: 14px; }",
	".framer-e9rxN .framer-u91032 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-e9rxN .framer-143prhv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 8px 0px 8px 0px; position: relative; text-decoration: none; width: 100%; }",
	".framer-e9rxN .framer-kunebk { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-e9rxN .framer-lw0ywb { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-e9rxN .framer-19u6pmc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; overflow: visible; padding: 12px 24px 12px 24px; position: relative; text-decoration: none; width: min-content; }",
	".framer-e9rxN .framer-8om0te { aspect-ratio: 4 / 1; flex: none; height: 100%; position: relative; text-decoration: none; width: var(--framer-aspect-ratio-supported, 800px); }",
	".framer-e9rxN .framer-29s8zc, .framer-e9rxN .framer-5vzw3d { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-e9rxN .framer-15jnnan { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 8px 12px 8px 12px; position: relative; text-decoration: none; width: min-content; }",
	".framer-e9rxN .framer-qfpb8, .framer-e9rxN .framer-eylbnf { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 24px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 24px; }",
	".framer-e9rxN .framer-16bijsw, .framer-e9rxN .framer-zfyxe1, .framer-e9rxN .framer-1h6gvk4 { flex: none; height: 2px; left: calc(50.00000000000002% - 20px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 2px / 2); width: 20px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-e9rxN .framer-1qz0zq7 { flex: none; height: 2px; left: calc(50.00000000000002% - 20px / 2); overflow: hidden; position: absolute; top: calc(25.00000000000002% - 2px / 2); width: 20px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-e9rxN .framer-1sxtqv7 { flex: none; height: 2px; left: calc(50.00000000000002% - 20px / 2); overflow: hidden; position: absolute; top: calc(75.00000000000003% - 2px / 2); width: 20px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-e9rxN .framer-ljlhhe { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: 30px; justify-content: space-between; max-width: 1200px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-e9rxN .framer-5pij6m { aspect-ratio: 4 / 1; flex: none; height: 100%; position: relative; width: var(--framer-aspect-ratio-supported, 800px); }",
	".framer-e9rxN .framer-9nd0i6 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 4px 20px 20px 20px; position: relative; width: 1px; }",
	".framer-e9rxN .framer-6zyxr8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; min-height: 201px; overflow: visible; padding: 0px 0px 0px 20px; position: relative; text-decoration: none; width: 100%; }",
	".framer-e9rxN .framer-b6p5t, .framer-e9rxN .framer-1cfrgd3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 20px; position: relative; text-decoration: none; width: 100%; }",
	".framer-e9rxN .framer-k0hqrv { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; overflow: visible; padding: 12px 0px 12px 0px; position: relative; width: 1px; }",
	".framer-e9rxN .framer-1xcjfd0 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-e9rxN.framer-v-ou95mp.framer-dxvjkb { flex-direction: column; height: auto; min-height: 54px; overflow: hidden; padding: 12px 16px 12px 16px; width: 100%; }",
	".framer-e9rxN.framer-v-ou95mp .framer-104j7s6 { align-items: center; flex: none; height: 30px; max-width: none; min-height: 30px; width: 100%; }",
	".framer-e9rxN.framer-v-ou95mp .framer-8om0te { flex: none; height: 30px; max-width: 120px; order: 3; width: 120px; }",
	".framer-e9rxN.framer-v-ou95mp .framer-29s8zc { order: 5; }",
	".framer-e9rxN.framer-v-1uivldt.framer-dxvjkb, .framer-e9rxN.framer-v-qqp9ex.framer-dxvjkb, .framer-e9rxN.framer-v-184jsh9.framer-dxvjkb { flex-direction: column; gap: 0px; height: auto; max-height: 100dvh; justify-content: flex-start; overflow-x: hidden; overflow-y: auto; -webkit-overflow-scrolling: touch; overscroll-behavior: contain; padding: 12px 16px 24px 16px; position: relative; width: 100%; z-index: 50; }",
	".framer-e9rxN .framer-mobile-open-panel { width: 100%; will-change: height, opacity; }",
	".framer-e9rxN .framer-mobile-open-panel .framer-ljlhhe, .framer-e9rxN .framer-mobile-open-panel .framer-9nd0i6, .framer-e9rxN .framer-mobile-open-panel .framer-k0hqrv { width: 100%; }",
	".framer-e9rxN.framer-v-1uivldt .framer-ljlhhe, .framer-e9rxN.framer-v-qqp9ex .framer-ljlhhe, .framer-e9rxN.framer-v-184jsh9 .framer-ljlhhe { background-color: rgb(23, 35, 30); flex: none; height: 30px; padding-bottom: 8px; position: sticky; top: 0; width: 100%; z-index: 2; }",
	".framer-e9rxN.framer-v-1uivldt .framer-9nd0i6, .framer-e9rxN.framer-v-qqp9ex .framer-9nd0i6, .framer-e9rxN.framer-v-184jsh9 .framer-9nd0i6 { flex: 1 1 auto; min-height: 0; overflow: visible; padding: 4px 20px 40px 20px; width: 100%; }",
	".framer-e9rxN .framer-mobile-resource-years-wrap, .framer-e9rxN .framer-mobile-investment-years-wrap { width: 100%; }",
	".framer-e9rxN.framer-v-qqp9ex .framer-mobile-resource-years-wrap { order: 1; }",
	".framer-e9rxN.framer-v-184jsh9 .framer-mobile-investment-years-wrap { order: 3; }",
	".framer-e9rxN.framer-v-1uivldt .framer-5pij6m, .framer-e9rxN.framer-v-qqp9ex .framer-5pij6m, .framer-e9rxN.framer-v-184jsh9 .framer-5pij6m { flex: none; height: 30px; max-width: 120px; order: 2; text-decoration: none; width: 120px; }",
	".framer-e9rxN.framer-v-1uivldt .framer-5vzw3d, .framer-e9rxN.framer-v-qqp9ex .framer-5vzw3d, .framer-e9rxN.framer-v-184jsh9 .framer-5vzw3d { order: 4; }",
	".framer-e9rxN.framer-v-1uivldt .framer-1123vbo, .framer-e9rxN.framer-v-1uivldt .framer-5nf8yk, .framer-e9rxN.framer-v-qqp9ex .framer-1123vbo, .framer-e9rxN.framer-v-qqp9ex .framer-5nf8yk, .framer-e9rxN.framer-v-184jsh9 .framer-1123vbo, .framer-e9rxN.framer-v-184jsh9 .framer-5nf8yk { cursor: pointer; }",
	".framer-e9rxN.framer-v-qqp9ex .framer-1123vbo { order: 0; }",
	".framer-e9rxN.framer-v-1uivldt .framer-k0hqrv, .framer-e9rxN.framer-v-qqp9ex .framer-k0hqrv, .framer-e9rxN.framer-v-184jsh9 .framer-k0hqrv { flex: none; text-decoration: none; width: 100%; }",
	".framer-e9rxN.framer-v-qqp9ex .framer-5pij6m, .framer-e9rxN.framer-v-184jsh9 .framer-5pij6m { order: 2; text-decoration: none; }",
	".framer-e9rxN.framer-v-qqp9ex .framer-6zyxr8 { min-height: unset; }",
	".framer-e9rxN.framer-v-qqp9ex .framer-mobile-resource-fy-0 { order: 1; }",
	".framer-e9rxN.framer-v-qqp9ex .framer-mobile-resource-fy-1 { order: 2; }",
	".framer-e9rxN.framer-v-qqp9ex .framer-2cydrd { order: 3; }",
	".framer-e9rxN.framer-v-qqp9ex .framer-5nf8yk { order: 4; }",
	".framer-e9rxN.framer-v-qqp9ex .framer-1umy14 { order: 5; }",
	".framer-e9rxN.framer-v-qqp9ex .framer-1addgu7 { order: 6; }",
	".framer-e9rxN.framer-v-184jsh9 .framer-1123vbo { cursor: pointer; order: 0; }",
	".framer-e9rxN.framer-v-184jsh9 .framer-2cydrd { order: 1; }",
	".framer-e9rxN.framer-v-184jsh9 .framer-5nf8yk { order: 2; }",
	".framer-e9rxN.framer-v-184jsh9 .framer-mobile-fy-0 { order: 3; }",
	".framer-e9rxN.framer-v-184jsh9 .framer-mobile-fy-1 { order: 4; }",
	".framer-e9rxN.framer-v-184jsh9 .framer-mobile-fy-2 { order: 5; }",
	".framer-e9rxN.framer-v-184jsh9 .framer-mobile-fy-3 { order: 6; }",
	".framer-e9rxN.framer-v-184jsh9 .framer-1umy14 { order: 7; }",
	".framer-e9rxN.framer-v-184jsh9 .framer-1addgu7 { order: 8; }",
	".framer-e9rxN .framer-mobile-fy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 20px; position: relative; text-decoration: none; width: 100%; }",
	...css,
	...css2,
	'.framer-e9rxN[data-border="true"]::after, .framer-e9rxN [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerdZbRlifrz = withCSS(Component, css3, "framer-e9rxN");
var stdin_default = FramerdZbRlifrz;
FramerdZbRlifrz.displayName = "Navigation";
FramerdZbRlifrz.defaultProps = {
	height: 94,
	width: 1200,
};
addPropertyControls(FramerdZbRlifrz, {
	variant: {
		options: ["hUMCu1JaQ", "zvqvmgi_X", "YmfvgTG50", "tpyWFivQj", "DRm9pRmsR"],
		optionTitles: ["Desktop", "Phone", "Phone Open", "Variant 5", "Variant 6"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerdZbRlifrz,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Satoshi",
					source: "fontshare",
					style: "normal",
					uiFamilyName: "Satoshi",
					url: "/fonts/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Satoshi",
					source: "fontshare",
					style: "normal",
					uiFamilyName: "Satoshi",
					url: "/fonts/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Satoshi",
					source: "fontshare",
					style: "normal",
					uiFamilyName: "Satoshi",
					url: "/fonts/KFIAZD4RUMEZIYV6FQ3T3GP5PDBDB6JY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:navigation
import { jsx } from "react/jsx-runtime";
var locales = [];
var DESKTOP_MQ = "(min-width: 1280px)";

function useIsDesktopNav() {
	const [isDesktop, setIsDesktop] = React.useState(() =>
		typeof window !== "undefined" ? window.matchMedia(DESKTOP_MQ).matches : true,
	);
	React.useEffect(() => {
		const mq = window.matchMedia(DESKTOP_MQ);
		const onChange = () => setIsDesktop(mq.matches);
		onChange();
		mq.addEventListener("change", onChange);
		return () => mq.removeEventListener("change", onChange);
	}, []);
	return isDesktop;
}

/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"af460206e137e8d824a96fddb1ea9788b0ffdc50cd99b3f451f16d44c1636491"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavigationFramerComponent for desktop vs phone. Avoids WithFramerBreakpoints
 * so the mobile open/close variants are not reset by a controlled breakpoint variant.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", variants: _variants, ...rest }) => {
	const isDesktop = useIsDesktopNav();
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"af460206e137e8d824a96fddb1ea9788b0ffdc50cd99b3f451f16d44c1636491"
			}
			locale={locale}
			locales={locales}
		>
			{isDesktop ? (
				<div
					className="framer-nav-fixed-slot"
					style={{ width: "100%", paddingTop: 94, boxSizing: "border-box" }}
				>
					{jsx(
						stdin_default,
						{
							...rest,
							variant: "Desktop",
						},
						"desktop",
					)}
				</div>
			) : (
				jsx(
					stdin_default,
					{
						...rest,
						variant: "Phone",
					},
					"mobile",
				)
			)}
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var navigation_default = ComponentWithRoot;
export { navigation_default as default };
