// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project af460206e137e8d8 "Sapient", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Desktop-sm' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-PZVC6U2W.js";

// virtual:privacy-policy
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:/framer-cms/modules/tAXnQFHK2aIb6EFcnUWd/OvLKTaUXJmFpVnI7NL7I/Htcz4VEv0.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["OIUCUi3hF", "HDvmAcwtz", "EpPrzurrg", "jcRzioFyf"];
var serializationHash = "framer-Gh3tB";
var variantClassNames = {
	EpPrzurrg: "framer-v-5cm550",
	HDvmAcwtz: "framer-v-1thdt44",
	jcRzioFyf: "framer-v-1lp1sj4",
	OIUCUi3hF: "framer-v-nk61jo",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Desktop-sm": "HDvmAcwtz",
	Desktop: "OIUCUi3hF",
	Phone: "jcRzioFyf",
	Tablet: "EpPrzurrg",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "OIUCUi3hF",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "OIUCUi3hF",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-nk61jo",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"OIUCUi3hF"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								EpPrzurrg: {
									"data-framer-name": "Tablet",
								},
								HDvmAcwtz: {
									"data-framer-name": "Desktop-sm",
								},
								jcRzioFyf: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-17h6a9b"}
							data-framer-name={"Frame 427322166"}
							layoutDependency={layoutDependency}
							layoutId={"kGJtDqKfh"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1oehaj"}
								data-framer-name={"Privacy Policy"}
								fonts={["GF;Plus Jakarta Sans-700"]}
								layoutDependency={layoutDependency}
								layoutId={"xasRxEQgo"}
								style={{
									"--extracted-r6o4lv": "rgb(15, 23, 42)",
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										jcRzioFyf: {
											children: (
												<React.Fragment>
													<motion.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
															"--framer-font-family":
																'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
															"--framer-font-size": "24px",
															"--framer-font-weight": "700",
															"--framer-letter-spacing": "0.01em",
															"--framer-line-height": "120%",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(15, 23, 42))",
														}}
													>
														{"Privacy Policy"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										dir={"auto"}
										style={{
											"--font-selector": "R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
											"--framer-font-family":
												'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
											"--framer-font-size": "56px",
											"--framer-font-weight": "700",
											"--framer-letter-spacing": "0.01em",
											"--framer-line-height": "120%",
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(15, 23, 42))",
										}}
									>
										{"Privacy Policy"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-7832zx"}
								data-framer-name={
									"Every week we invite some of the most influential people from around the the world to discuss about the future of finance in india and how important financial knowledge really is."
								}
								fonts={["FS;Satoshi-medium"]}
								layoutDependency={layoutDependency}
								layoutId={"Fdgjqlmx6"}
								style={{
									"--extracted-r6o4lv": "rgb(51, 65, 85)",
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										jcRzioFyf: {
											children: (
												<React.Fragment>
													<motion.p
														dir={"auto"}
														style={{
															"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
															"--framer-font-family":
																'"Satoshi", "Satoshi Placeholder", sans-serif',
															"--framer-font-size": "12px",
															"--framer-font-weight": "500",
															"--framer-letter-spacing": "0.01em",
															"--framer-line-height": "150%",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(51, 65, 85))",
														}}
													>
														{"Last updated: November 11, 2024"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										dir={"auto"}
										style={{
											"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
											"--framer-font-family":
												'"Satoshi", "Satoshi Placeholder", sans-serif',
											"--framer-font-weight": "500",
											"--framer-letter-spacing": "0.01em",
											"--framer-line-height": "150%",
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(51, 65, 85))",
										}}
									>
										{"Last updated: November 11, 2024"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-19un3ct"}
							data-framer-name={
								"Details of Scheme level commission on Mutual funds are available with the Relationship Managers and would be produced on demand. This is on a best effort basis and rates are updated as and when actual rates are received from AMCs. We are a NISM certified / AMFI registered mutual fund distributor and not an RIA. We get compensated / incentivised by AMCs. We don't charge any fees for our services."
							}
							fonts={["FS;Satoshi-medium"]}
							layoutDependency={layoutDependency}
							layoutId={"aUoK4tpuP"}
							style={{
								"--extracted-r6o4lv": "rgb(51, 65, 85)",
								"--framer-paragraph-spacing": "0px",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									jcRzioFyf: {
										children: (
											<React.Fragment>
												<motion.p
													dir={"auto"}
													style={{
														"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
														"--framer-font-family":
															'"Satoshi", "Satoshi Placeholder", sans-serif',
														"--framer-font-size": "12px",
														"--framer-font-weight": "500",
														"--framer-letter-spacing": "0.01em",
														"--framer-line-height": "150%",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(51, 65, 85))",
													}}
												>
													{
														"Privacy Policy For Sapient, your privacy is utmost important. While information is extremely important to enable us to provide you high quality service, our most important aim to win customers' and sub distributors\u2019 trust. Keeping your information secure and using it only as you would want us to, is a top priority for Sapient. The purpose of this privacy policy is to set out the manner and purposes for which Sapient will obtain and process your personal information. Sapient is committed to safeguard all your confidential information. The following describes our current policies regarding collection, use and disclosure of your personal information which we receive in the course of you accessing our Website and any other services provided through this Website. By using this Website, you are consenting to the collection and use of your personal information in the way we describe in this policy and our Terms."
													}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									dir={"auto"}
									style={{
										"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
										"--framer-font-family":
											'"Satoshi", "Satoshi Placeholder", sans-serif',
										"--framer-font-size": "20px",
										"--framer-font-weight": "500",
										"--framer-letter-spacing": "0.01em",
										"--framer-line-height": "150%",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(51, 65, 85))",
									}}
								>
									{
										"Privacy Policy For Sapient, your privacy is utmost important. While information is extremely important to enable us to provide you high quality service, our most important aim to win customers' and sub distributors\u2019 trust. Keeping your information secure and using it only as you would want us to, is a top priority for Sapient. The purpose of this privacy policy is to set out the manner and purposes for which Sapient will obtain and process your personal information. Sapient is committed to safeguard all your confidential information. The following describes our current policies regarding collection, use and disclosure of your personal information which we receive in the course of you accessing our Website and any other services provided through this Website. By using this Website, you are consenting to the collection and use of your personal information in the way we describe in this policy and our Terms."
									}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1bdcsem"}
							data-framer-name={
								"Details of Scheme level commission on Mutual funds are available with the Relationship Managers and would be produced on demand. This is on a best effort basis and rates are updated as and when actual rates are received from AMCs. We are a NISM certified / AMFI registered mutual fund distributor and not an RIA. We get compensated / incentivised by AMCs. We don't charge any fees for our services."
							}
							fonts={["FS;Satoshi-medium"]}
							layoutDependency={layoutDependency}
							layoutId={"CiMpD04_P"}
							style={{
								"--extracted-r6o4lv": "rgb(51, 65, 85)",
								"--framer-paragraph-spacing": "0px",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									jcRzioFyf: {
										children: (
											<React.Fragment>
												<motion.p
													dir={"auto"}
													style={{
														"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
														"--framer-font-family":
															'"Satoshi", "Satoshi Placeholder", sans-serif',
														"--framer-font-size": "12px",
														"--framer-font-weight": "500",
														"--framer-letter-spacing": "0.01em",
														"--framer-line-height": "150%",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(51, 65, 85))",
													}}
												>
													{
														"This Website does not collect personally identifiable information about you except when you specifically and knowingly provide it. Sapient may make use your personally identifiable information to operate the sites and services and to inform you of new features, services, and products from Sapient and its affiliates. Sapient, though may collect your personal information when you register or provide any feedback on this Website. Sapient has taken all necessary and reasonable measures to protect the confidentiality of the customer information and its transmission through the World Wide Web / internet. However, Sapient or any of its directors/ associates /employees / affiliates/ associates/ holding company/ subsidiaries/ agents cannot be held liable or responsible for disclosure of the confidential information when in accordance with any law or regulatory authorities or judiciary needing it. However, it is sometimes necessary to provide personally identifiable information about you to a third party, business partners and/or organisation that perform services on our behalf. Such information is only provided in accordance with the law and that our employees, agents and/or affiliates are required to treat the information confidentially and use it exclusively for the purpose for which it is provided."
													}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									dir={"auto"}
									style={{
										"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
										"--framer-font-family":
											'"Satoshi", "Satoshi Placeholder", sans-serif',
										"--framer-font-size": "20px",
										"--framer-font-weight": "500",
										"--framer-letter-spacing": "0.01em",
										"--framer-line-height": "150%",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(51, 65, 85))",
									}}
								>
									{
										"This Website does not collect personally identifiable information about you except when you specifically and knowingly provide it. Sapient may make use your personally identifiable information to operate the sites and services and to inform you of new features, services, and products from Sapient and its affiliates. Sapient, though may collect your personal information when you register or provide any feedback on this Website. Sapient has taken all necessary and reasonable measures to protect the confidentiality of the customer information and its transmission through the World Wide Web / internet. However, Sapient or any of its directors/ associates /employees / affiliates/ associates/ holding company/ subsidiaries/ agents cannot be held liable or responsible for disclosure of the confidential information when in accordance with any law or regulatory authorities or judiciary needing it. However, it is sometimes necessary to provide personally identifiable information about you to a third party, business partners and/or organisation that perform services on our behalf. Such information is only provided in accordance with the law and that our employees, agents and/or affiliates are required to treat the information confidentially and use it exclusively for the purpose for which it is provided."
									}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-o0l323"}
							data-framer-name={
								"Details of Scheme level commission on Mutual funds are available with the Relationship Managers and would be produced on demand. This is on a best effort basis and rates are updated as and when actual rates are received from AMCs. We are a NISM certified / AMFI registered mutual fund distributor and not an RIA. We get compensated / incentivised by AMCs. We don't charge any fees for our services."
							}
							fonts={["FS;Satoshi-medium"]}
							layoutDependency={layoutDependency}
							layoutId={"krwn1KTlz"}
							style={{
								"--extracted-r6o4lv": "rgb(51, 65, 85)",
								"--framer-paragraph-spacing": "0px",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									jcRzioFyf: {
										children: (
											<React.Fragment>
												<motion.p
													dir={"auto"}
													style={{
														"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
														"--framer-font-family":
															'"Satoshi", "Satoshi Placeholder", sans-serif',
														"--framer-font-size": "12px",
														"--framer-font-weight": "500",
														"--framer-letter-spacing": "0.01em",
														"--framer-line-height": "150%",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(51, 65, 85))",
													}}
												>
													{
														"We do not share your personal information except where permitted by law or for lawful purposes. Sapient may collect public and/or non-public information, personal and/or financial, about you for its lawful business or operational purposes from you or your authorised agents through application form(s), financial information, risk profile, investment selection, beneficiary information and any other documentation supporting the said information. Sapient sends the account statements or financial information pertaining to the clients/investors to be sent over the internet and only through a secure mode. Sapient also ensures that the parties to whom such aforesaid information/data is shared have confidentiality provisions and high levels of security practices, controls and procedures to ensure its protection. Notwithstanding anything mentioned in the Terms, Sapient shall not be responsible or liable, either directly or indirectly, for the authenticity, accuracy of the personal, financial information or any other information submitted by you, for its misuse, not attributable to the acts of Sapient, at any time and in any manner whatsoever."
													}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									dir={"auto"}
									style={{
										"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
										"--framer-font-family":
											'"Satoshi", "Satoshi Placeholder", sans-serif',
										"--framer-font-size": "20px",
										"--framer-font-weight": "500",
										"--framer-letter-spacing": "0.01em",
										"--framer-line-height": "150%",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(51, 65, 85))",
									}}
								>
									{
										"We do not share your personal information except where permitted by law or for lawful purposes. Sapient may collect public and/or non-public information, personal and/or financial, about you for its lawful business or operational purposes from you or your authorised agents through application form(s), financial information, risk profile, investment selection, beneficiary information and any other documentation supporting the said information. Sapient sends the account statements or financial information pertaining to the clients/investors to be sent over the internet and only through a secure mode. Sapient also ensures that the parties to whom such aforesaid information/data is shared have confidentiality provisions and high levels of security practices, controls and procedures to ensure its protection. Notwithstanding anything mentioned in the Terms, Sapient shall not be responsible or liable, either directly or indirectly, for the authenticity, accuracy of the personal, financial information or any other information submitted by you, for its misuse, not attributable to the acts of Sapient, at any time and in any manner whatsoever."
									}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1jo6jk1"}
							data-framer-name={
								"Details of Scheme level commission on Mutual funds are available with the Relationship Managers and would be produced on demand. This is on a best effort basis and rates are updated as and when actual rates are received from AMCs. We are a NISM certified / AMFI registered mutual fund distributor and not an RIA. We get compensated / incentivised by AMCs. We don't charge any fees for our services."
							}
							fonts={["FS;Satoshi-medium"]}
							layoutDependency={layoutDependency}
							layoutId={"C1jgg3EuS"}
							style={{
								"--extracted-r6o4lv": "rgb(51, 65, 85)",
								"--framer-paragraph-spacing": "0px",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									jcRzioFyf: {
										children: (
											<React.Fragment>
												<motion.p
													dir={"auto"}
													style={{
														"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
														"--framer-font-family":
															'"Satoshi", "Satoshi Placeholder", sans-serif',
														"--framer-font-size": "12px",
														"--framer-font-weight": "500",
														"--framer-letter-spacing": "0.01em",
														"--framer-line-height": "150%",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(51, 65, 85))",
													}}
												>
													{
														"In case you feel that any information provided by you is inaccurate / deficient or requires updating, then you shall ensure to correct or amend such information as soon as possible by getting in touch with us. Sapient will at all times endeavour to handle transactions efficiently and to resolve any investor or sub-distributor\u2019s grievances promptly. Sapient reserves the right to modify sections of this Privacy Policy at any time without giving any prior notice. Please check this Policy from time to time for any changes. We aim to offer you the very best personal service and the products you need. Your views are important to us. Also, If at any time you believe that Sapient or its users have not adhered to these principles - please help us by letting us know of any way that we can improve our service to you by contacting us at service@sapient.in"
													}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									dir={"auto"}
									style={{
										"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
										"--framer-font-family":
											'"Satoshi", "Satoshi Placeholder", sans-serif',
										"--framer-font-size": "20px",
										"--framer-font-weight": "500",
										"--framer-letter-spacing": "0.01em",
										"--framer-line-height": "150%",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(51, 65, 85))",
									}}
								>
									{
										"In case you feel that any information provided by you is inaccurate / deficient or requires updating, then you shall ensure to correct or amend such information as soon as possible by getting in touch with us. Sapient will at all times endeavour to handle transactions efficiently and to resolve any investor or sub-distributor\u2019s grievances promptly. Sapient reserves the right to modify sections of this Privacy Policy at any time without giving any prior notice. Please check this Policy from time to time for any changes. We aim to offer you the very best personal service and the products you need. Your views are important to us. Also, If at any time you believe that Sapient or its users have not adhered to these principles - please help us by letting us know of any way that we can improve our service to you by contacting us at service@sapient.in"
									}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Gh3tB.framer-1kqxrcw, .framer-Gh3tB .framer-1kqxrcw { display: block; }",
	".framer-Gh3tB.framer-nk61jo { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1200px; }",
	".framer-Gh3tB .framer-17h6a9b { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: 107px; justify-content: flex-start; max-width: 1200px; overflow: visible; padding: 0px; position: relative; width: 1200px; }",
	".framer-Gh3tB .framer-1oehaj { flex: 1 0 0px; height: 1px; position: relative; white-space: pre-wrap; width: 929px; word-break: break-word; word-wrap: break-word; }",
	".framer-Gh3tB .framer-7832zx { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-Gh3tB .framer-19un3ct, .framer-Gh3tB .framer-1bdcsem, .framer-Gh3tB .framer-o0l323, .framer-Gh3tB .framer-1jo6jk1 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 1200px; word-break: break-word; word-wrap: break-word; }",
	".framer-Gh3tB.framer-v-1thdt44.framer-nk61jo { padding: 0px 24px 0px 24px; }",
	".framer-Gh3tB.framer-v-1thdt44 .framer-17h6a9b, .framer-Gh3tB.framer-v-1thdt44 .framer-1oehaj, .framer-Gh3tB.framer-v-1thdt44 .framer-19un3ct, .framer-Gh3tB.framer-v-1thdt44 .framer-1bdcsem, .framer-Gh3tB.framer-v-1thdt44 .framer-o0l323, .framer-Gh3tB.framer-v-1thdt44 .framer-1jo6jk1, .framer-Gh3tB.framer-v-5cm550 .framer-17h6a9b, .framer-Gh3tB.framer-v-5cm550 .framer-19un3ct, .framer-Gh3tB.framer-v-5cm550 .framer-1bdcsem, .framer-Gh3tB.framer-v-5cm550 .framer-o0l323, .framer-Gh3tB.framer-v-5cm550 .framer-1jo6jk1, .framer-Gh3tB.framer-v-1lp1sj4 .framer-19un3ct, .framer-Gh3tB.framer-v-1lp1sj4 .framer-1bdcsem, .framer-Gh3tB.framer-v-1lp1sj4 .framer-o0l323, .framer-Gh3tB.framer-v-1lp1sj4 .framer-1jo6jk1 { width: 100%; }",
	".framer-Gh3tB.framer-v-5cm550.framer-nk61jo { padding: 0px 24px 0px 24px; width: 810px; }",
	".framer-Gh3tB.framer-v-1lp1sj4.framer-nk61jo { gap: 40px; padding: 0px 24px 0px 24px; width: 390px; }",
	".framer-Gh3tB.framer-v-1lp1sj4 .framer-17h6a9b { height: min-content; width: 100%; }",
	".framer-Gh3tB.framer-v-1lp1sj4 .framer-1oehaj { flex: none; height: auto; width: 100%; }",
];
var FramerHtcz4VEv0 = withCSS(Component, css, "framer-Gh3tB");
var stdin_default = FramerHtcz4VEv0;
FramerHtcz4VEv0.displayName = "PrivacyPolicy";
FramerHtcz4VEv0.defaultProps = {
	height: 1477,
	width: 1200,
};
addPropertyControls(FramerHtcz4VEv0, {
	variant: {
		options: ["OIUCUi3hF", "HDvmAcwtz", "EpPrzurrg", "jcRzioFyf"],
		optionTitles: ["Desktop", "Desktop-sm", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerHtcz4VEv0,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Plus Jakarta Sans",
					source: "google",
					style: "normal",
					uiFamilyName: "Plus Jakarta Sans",
					url: "/fonts/LDIbaomQNQcsA88c7O9yZ4KMCoOg4IA6-91aHEjcWuA_TknNTxXUEKi4Rw.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Satoshi",
					source: "fontshare",
					style: "normal",
					uiFamilyName: "Satoshi",
					url: "/fonts/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2",
					weight: "500",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:privacy-policy
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "jcRzioFyf",
	md: "EpPrzurrg",
	xl: "HDvmAcwtz",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"af460206e137e8d824a96fddb1ea9788b0ffdc50cd99b3f451f16d44c1636491"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PrivacyPolicyFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"af460206e137e8d824a96fddb1ea9788b0ffdc50cd99b3f451f16d44c1636491"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var privacy_policy_default = ComponentWithRoot;
export { privacy_policy_default as default };
