// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project af460206e137e8d8 "Sapient", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Desktop-sm' | 'Tablet' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-PZVC6U2W.js";

// virtual:success-page
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:/framer-cms/modules/Py04aD9lMTXZfEJUxzxS/QZIr3jo84bLLDJHwQB4D/qFoYzh6nE.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	FormContainer,
	Link,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["HQKIfKA8n", "Jj3qMI8by", "VNUDYjjKk"];
var serializationHash = "framer-ys8Iy";
var variantClassNames = {
	HQKIfKA8n: "framer-v-1qfdn6q",
	Jj3qMI8by: "framer-v-2qz9br",
	VNUDYjjKk: "framer-v-1boap18",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Desktop-sm": "Jj3qMI8by",
	Desktop: "HQKIfKA8n",
	Tablet: "VNUDYjjKk",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "HQKIfKA8n",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "HQKIfKA8n",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1qfdn6q",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"HQKIfKA8n"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								Jj3qMI8by: {
									"data-framer-name": "Desktop-sm",
								},
								VNUDYjjKk: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1e5bbxs"}
							data-framer-name={"Frame 1430105539"}
							layoutDependency={layoutDependency}
							layoutId={"ZDg8rIuXi"}
						>
							<FormContainer
								action={
									"https://api.framer.com/forms/v1/forms/cac509a6-e70e-4828-be20-ed3e10080d6e/submit"
								}
								className={"framer-1fnzt57"}
								layoutDependency={layoutDependency}
								layoutId={"xCXDlqCP1"}
								nodeId={"xCXDlqCP1"}
								redirectUrl={"/"}
							>
								{(formState) => (
									<_Fragment>
										<motion.div
											className={"framer-6ghvb5"}
											data-framer-name={"Frame 1430105530"}
											layoutDependency={layoutDependency}
											layoutId={"ukDBKrxRQ"}
										>
											<SVG
												className={"framer-1jo88g5"}
												data-framer-name={"graphic"}
												fill={"rgb(23, 35, 30)"}
												intrinsicHeight={24}
												intrinsicWidth={24}
												layoutDependency={layoutDependency}
												layoutId={"jm5yUfWz5"}
												svg={
													'<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="icon icon-tabler icons-tabler-filled icon-tabler-circle-check"><path d="M0 0h24v24H0z" fill="none"/><path d="M17 3.34a10 10 0 1 1-14.995 8.984L2 12l.005-.324A10 10 0 0 1 17 3.34zm-1.293 5.953a1 1 0 0 0-1.32-.083l-.094.083L11 12.585l-1.293-1.292-.094-.083a1 1 0 0 0-1.403 1.403l.083.094 2 2 .094.083a1 1 0 0 0 1.226 0l.094-.083 4-4 .083-.094a1 1 0 0 0-.083-1.32z"/></svg>'
												}
												withExternalLayout={true}
											/>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-wvpz6y"}
												data-framer-name={"Let\u2019s talk"}
												fonts={["GF;Plus Jakarta Sans-700"]}
												layoutDependency={layoutDependency}
												layoutId={"PWJ7XwSXl"}
												style={{
													"--extracted-r6o4lv": "rgb(23, 35, 30)",
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
															"--framer-font-family":
																'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
															"--framer-font-size": "36px",
															"--framer-font-weight": "700",
															"--framer-line-height": "135%",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(23, 35, 30))",
														}}
													>
														{"Thank You"}
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1nggm10"}
												data-framer-name={
													"We're excited to learn more about your goals & craft a unique plan to achieve them, \u2018together\u2019."
												}
												fonts={["FS;Satoshi-medium"]}
												layoutDependency={layoutDependency}
												layoutId={"ouJBi2Y3r"}
												style={{
													"--extracted-r6o4lv": "rgb(23, 35, 30)",
													"--framer-paragraph-spacing": "0px",
													opacity: 0.7,
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														dir={"auto"}
														style={{
															"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
															"--framer-font-family":
																'"Satoshi", "Satoshi Placeholder", sans-serif',
															"--framer-font-weight": "500",
															"--framer-line-height": "155%",
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(23, 35, 30))",
														}}
													>
														{"You have successfully submitted your response!"}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
										<Link
											href={{
												webPageId: "mighqlLao",
											}}
											motionChild={true}
											nodeId={"lKc7zo6qV"}
											scopeId={"qFoYzh6nE"}
										>
											<motion.a
												className={"framer-1rt264x framer-1rnzl88"}
												data-framer-name={"Button Copy 2"}
												data-reset={"button"}
												layoutDependency={layoutDependency}
												layoutId={"lKc7zo6qV"}
												style={{
													backgroundColor: "rgb(164, 207, 107)",
													borderBottomLeftRadius: 10,
													borderBottomRightRadius: 10,
													borderTopLeftRadius: 10,
													borderTopRightRadius: 10,
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-nivflh"}
													fonts={["Inter-SemiBold"]}
													layoutDependency={layoutDependency}
													layoutId={"dHhtrTVpd"}
													style={{
														"--extracted-r6o4lv": "rgb(24, 35, 30)",
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															dir={"auto"}
															style={{
																"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
																"--framer-font-size": "14px",
																"--framer-font-weight": "600",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(24, 35, 30))",
															}}
														>
															{"Submit another response"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.a>
										</Link>
									</_Fragment>
								)}
							</FormContainer>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ys8Iy.framer-1rnzl88, .framer-ys8Iy .framer-1rnzl88 { display: block; }",
	".framer-ys8Iy.framer-1qfdn6q { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; max-width: 1440px; overflow: visible; padding: 0px; position: relative; width: 1440px; }",
	".framer-ys8Iy .framer-1e5bbxs { align-content: flex-start; align-items: flex-start; align-self: stretch; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: auto; justify-content: center; overflow: visible; padding: 64px 120px 64px 120px; position: relative; width: 728px; }",
	".framer-ys8Iy .framer-1fnzt57 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-ys8Iy .framer-6ghvb5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-ys8Iy .framer-1jo88g5 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 92px); position: relative; width: 92px; }",
	".framer-ys8Iy .framer-wvpz6y { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-ys8Iy .framer-1nggm10 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-ys8Iy .framer-1rt264x { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 40px; justify-content: center; overflow: visible; padding: 16px 0px 16px 0px; position: relative; text-decoration: none; width: 100%; }",
	".framer-ys8Iy .framer-nivflh { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-ys8Iy.framer-v-2qz9br.framer-1qfdn6q { align-content: center; align-items: center; max-width: 1200px; width: 1200px; }",
	".framer-ys8Iy.framer-v-2qz9br .framer-1e5bbxs { align-content: center; align-items: center; flex: 1 0 0px; padding: 64px 24px 64px 24px; width: 1px; }",
	".framer-ys8Iy.framer-v-2qz9br .framer-1fnzt57 { max-width: 540px; }",
	".framer-ys8Iy.framer-v-1boap18.framer-1qfdn6q { max-width: 1200px; width: 810px; }",
	".framer-ys8Iy.framer-v-1boap18 .framer-1e5bbxs { flex: 1 0 0px; max-width: 560px; padding: 48px 24px 48px 24px; width: 1px; }",
];
var FramerqFoYzh6nE = withCSS(Component, css, "framer-ys8Iy");
var stdin_default = FramerqFoYzh6nE;
FramerqFoYzh6nE.displayName = "SuccessPage";
FramerqFoYzh6nE.defaultProps = {
	height: 397,
	width: 1440,
};
addPropertyControls(FramerqFoYzh6nE, {
	variant: {
		options: ["HQKIfKA8n", "Jj3qMI8by", "VNUDYjjKk"],
		optionTitles: ["Desktop", "Desktop-sm", "Tablet"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerqFoYzh6nE,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Plus Jakarta Sans",
					source: "google",
					style: "normal",
					uiFamilyName: "Plus Jakarta Sans",
					url: "/fonts/LDIbaomQNQcsA88c7O9yZ4KMCoOg4IA6-91aHEjcWuA_TknNTxXUEKi4Rw.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Satoshi",
					source: "fontshare",
					style: "normal",
					uiFamilyName: "Satoshi",
					url: "/fonts/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "/fonts/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "/fonts/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "/fonts/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "/fonts/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "/fonts/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "/fonts/yDtI2UI8XcEg1W2je9XPN3Noo.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "/fonts/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
					weight: "600",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:success-page
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "VNUDYjjKk",
	xl: "HQKIfKA8n",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"af460206e137e8d824a96fddb1ea9788b0ffdc50cd99b3f451f16d44c1636491"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SuccessPageFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"af460206e137e8d824a96fddb1ea9788b0ffdc50cd99b3f451f16d44c1636491"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var success_page_default = ComponentWithRoot;
export { success_page_default as default };
