// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project af460206e137e8d8 "Sapient", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Desktop-sm' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-PZVC6U2W.js";

// virtual:terms-conditions
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:/framer-cms/modules/8FIReblOvKLeOYtJGTqc/FlMVlvHMLsjBd5W4d5kI/CqaHt9LUU.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["zmbniIlTF", "KSAhnboJQ", "D7mfxnUc5", "POugk4GoA"];
var serializationHash = "framer-nEI1x";
var variantClassNames = {
	D7mfxnUc5: "framer-v-1k0kr8x",
	KSAhnboJQ: "framer-v-jtj1gt",
	POugk4GoA: "framer-v-1vh6bxh",
	zmbniIlTF: "framer-v-ee8z4a",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Desktop-sm": "KSAhnboJQ",
	Desktop: "zmbniIlTF",
	Phone: "POugk4GoA",
	Tablet: "D7mfxnUc5",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "zmbniIlTF",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "zmbniIlTF",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-ee8z4a",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"zmbniIlTF"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								D7mfxnUc5: {
									"data-framer-name": "Tablet",
								},
								KSAhnboJQ: {
									"data-framer-name": "Desktop-sm",
								},
								POugk4GoA: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-tp6i2a"}
							data-framer-name={"Frame 427322166"}
							layoutDependency={layoutDependency}
							layoutId={"S4uXWEHAe"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-jiwtt7"}
								data-framer-name={"KYM : Know your manager"}
								fonts={["GF;Plus Jakarta Sans-700"]}
								layoutDependency={layoutDependency}
								layoutId={"WiG76Z6Gn"}
								style={{
									"--extracted-r6o4lv": "rgb(15, 23, 42)",
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										POugk4GoA: {
											children: (
												<React.Fragment>
													<motion.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
															"--framer-font-family":
																'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
															"--framer-font-size": "24px",
															"--framer-font-weight": "700",
															"--framer-letter-spacing": "0.01em",
															"--framer-line-height": "120%",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(15, 23, 42))",
														}}
													>
														{"Terms & Conditions"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										dir={"auto"}
										style={{
											"--font-selector": "R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
											"--framer-font-family":
												'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
											"--framer-font-size": "56px",
											"--framer-font-weight": "700",
											"--framer-letter-spacing": "0.01em",
											"--framer-line-height": "120%",
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(15, 23, 42))",
										}}
									>
										{"Terms & Conditions"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1yuu26p"}
								data-framer-name={
									"Every week we invite some of the most influential people from around the the world to discuss about the future of finance in india and how important financial knowledge really is."
								}
								fonts={["FS;Satoshi-medium"]}
								layoutDependency={layoutDependency}
								layoutId={"WFkiRqNsF"}
								style={{
									"--extracted-r6o4lv": "rgb(51, 65, 85)",
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										POugk4GoA: {
											children: (
												<React.Fragment>
													<motion.p
														dir={"auto"}
														style={{
															"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
															"--framer-font-family":
																'"Satoshi", "Satoshi Placeholder", sans-serif',
															"--framer-font-size": "12px",
															"--framer-font-weight": "500",
															"--framer-letter-spacing": "0.01em",
															"--framer-line-height": "150%",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(51, 65, 85))",
														}}
													>
														{"Last updated: November 11, 2024"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										dir={"auto"}
										style={{
											"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
											"--framer-font-family":
												'"Satoshi", "Satoshi Placeholder", sans-serif',
											"--framer-font-weight": "500",
											"--framer-letter-spacing": "0.01em",
											"--framer-line-height": "150%",
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(51, 65, 85))",
										}}
									>
										{"Last updated: November 11, 2024"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-3z5pam"}
							data-framer-name={
								"Details of Scheme level commission on Mutual funds are available with the Relationship Managers and would be produced on demand. This is on a best effort basis and rates are updated as and when actual rates are received from AMCs. We are a NISM certified / AMFI registered mutual fund distributor and not an RIA. We get compensated / incentivised by AMCs. We don't charge any fees for our services."
							}
							fonts={["FS;Satoshi-medium"]}
							layoutDependency={layoutDependency}
							layoutId={"JYKQqIvX5"}
							style={{
								"--extracted-r6o4lv": "rgb(51, 65, 85)",
								"--framer-paragraph-spacing": "0px",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									POugk4GoA: {
										children: (
											<React.Fragment>
												<motion.p
													dir={"auto"}
													style={{
														"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
														"--framer-font-family":
															'"Satoshi", "Satoshi Placeholder", sans-serif',
														"--framer-font-size": "12px",
														"--framer-font-weight": "500",
														"--framer-letter-spacing": "0.01em",
														"--framer-line-height": "150%",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(51, 65, 85))",
													}}
												>
													{
														'Terms of Use Please read these terms and conditions for use of the Website and its services ("hereinafter referred to as "Terms") carefully. By visiting the Website, you are agreeing to be bound by these Terms. If you do not agree to any of the terms mentioned herein, you should exit the Website immediately. If you continue to use the Website, it would be construed that the Terms mentioned on this Website are acceptable to you.'
													}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									dir={"auto"}
									style={{
										"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
										"--framer-font-family":
											'"Satoshi", "Satoshi Placeholder", sans-serif',
										"--framer-font-size": "20px",
										"--framer-font-weight": "500",
										"--framer-letter-spacing": "0.01em",
										"--framer-line-height": "150%",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(51, 65, 85))",
									}}
								>
									{
										'Terms of Use Please read these terms and conditions for use of the Website and its services ("hereinafter referred to as "Terms") carefully. By visiting the Website, you are agreeing to be bound by these Terms. If you do not agree to any of the terms mentioned herein, you should exit the Website immediately. If you continue to use the Website, it would be construed that the Terms mentioned on this Website are acceptable to you.'
									}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-zyfkv9"}
							data-framer-name={
								"Details of Scheme level commission on Mutual funds are available with the Relationship Managers and would be produced on demand. This is on a best effort basis and rates are updated as and when actual rates are received from AMCs. We are a NISM certified / AMFI registered mutual fund distributor and not an RIA. We get compensated / incentivised by AMCs. We don't charge any fees for our services."
							}
							fonts={["FS;Satoshi-medium"]}
							layoutDependency={layoutDependency}
							layoutId={"KeJyZj9MR"}
							style={{
								"--extracted-r6o4lv": "rgb(51, 65, 85)",
								"--framer-paragraph-spacing": "0px",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									POugk4GoA: {
										children: (
											<React.Fragment>
												<motion.p
													dir={"auto"}
													style={{
														"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
														"--framer-font-family":
															'"Satoshi", "Satoshi Placeholder", sans-serif',
														"--framer-font-size": "12px",
														"--framer-font-weight": "500",
														"--framer-letter-spacing": "0.01em",
														"--framer-line-height": "150%",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(51, 65, 85))",
													}}
												>
													{
														"Sapient reserves the right to remove or edit content of the Website, at any time, without notice to you. Kindly re-visit the Terms of use whenever you access the Website or use any service on the Website in order to stay updated with any changes to the Terms. By registering at the Website or by enrolling as its customer/investor or as a sub-distributor, directly or indirectly, you confirm that the information you provide, now or in the future, is accurate. Sapient reserves the right, in its sole discretion, to deny you access to this Website or any portion thereof without notice for any reason whatsoever. By allowing you the access to the Website, Sapient permits you only non-exclusive, non-transferable, non-assignable and limited right to access the Website."
													}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									dir={"auto"}
									style={{
										"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
										"--framer-font-family":
											'"Satoshi", "Satoshi Placeholder", sans-serif',
										"--framer-font-size": "20px",
										"--framer-font-weight": "500",
										"--framer-letter-spacing": "0.01em",
										"--framer-line-height": "150%",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(51, 65, 85))",
									}}
								>
									{
										"Sapient reserves the right to remove or edit content of the Website, at any time, without notice to you. Kindly re-visit the Terms of use whenever you access the Website or use any service on the Website in order to stay updated with any changes to the Terms. By registering at the Website or by enrolling as its customer/investor or as a sub-distributor, directly or indirectly, you confirm that the information you provide, now or in the future, is accurate. Sapient reserves the right, in its sole discretion, to deny you access to this Website or any portion thereof without notice for any reason whatsoever. By allowing you the access to the Website, Sapient permits you only non-exclusive, non-transferable, non-assignable and limited right to access the Website."
									}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-v6vijo"}
							data-framer-name={
								"Details of Scheme level commission on Mutual funds are available with the Relationship Managers and would be produced on demand. This is on a best effort basis and rates are updated as and when actual rates are received from AMCs. We are a NISM certified / AMFI registered mutual fund distributor and not an RIA. We get compensated / incentivised by AMCs. We don't charge any fees for our services."
							}
							fonts={["FS;Satoshi-medium"]}
							layoutDependency={layoutDependency}
							layoutId={"VZbRJiwAK"}
							style={{
								"--extracted-r6o4lv": "rgb(51, 65, 85)",
								"--framer-paragraph-spacing": "0px",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									POugk4GoA: {
										children: (
											<React.Fragment>
												<motion.p
													dir={"auto"}
													style={{
														"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
														"--framer-font-family":
															'"Satoshi", "Satoshi Placeholder", sans-serif',
														"--framer-font-size": "12px",
														"--framer-font-weight": "500",
														"--framer-letter-spacing": "0.01em",
														"--framer-line-height": "150%",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(51, 65, 85))",
													}}
												>
													{
														"Unauthorised use of Sapient's web site and systems, including, but not limited to, unauthorised entry into Sapient's systems, online accounts, client data or section, sub-distributors\u2019 data or section, misuse of passwords or misuse of any other information, is strictly prohibited. You shall not attempt to gain unauthorised access to this Website or any of our sites or service and computer systems or networks connected to it, through hacking. You have the responsibilities to keep your login credentials to this Website confidential and not share with anyone. In case for whatever reason, the information on your login credentials to this Website gets leaked or compromised and used, Sapient or its directors, employees, agents, vendors, affiliates, associates, holding or subsidiary company(ies) shall not be held responsible, accountable or liable for any damage or loss to you consequent to such leakage and/or usage of the login credentials to this Website. Sapient may use certain technology on Website to collect information from visitors and may compile aggregate statistical information about how visitors use this Website, including information relating to the frequency of visits, the average length of visits, which pages are viewed during a visit. Sapient uses this information to improve its Website content and performance. No individually identifiable information is collected for this purpose and Sapient does not monitor individual visitor behaviour. All the information and contents on the Website is the exclusive property of Sapient and it is the sole owner of all the intellectual properties, rights, titles and interests."
													}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									dir={"auto"}
									style={{
										"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
										"--framer-font-family":
											'"Satoshi", "Satoshi Placeholder", sans-serif',
										"--framer-font-size": "20px",
										"--framer-font-weight": "500",
										"--framer-letter-spacing": "0.01em",
										"--framer-line-height": "150%",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(51, 65, 85))",
									}}
								>
									{
										"Unauthorised use of Sapient's web site and systems, including, but not limited to, unauthorised entry into Sapient's systems, online accounts, client data or section, sub-distributors\u2019 data or section, misuse of passwords or misuse of any other information, is strictly prohibited. You shall not attempt to gain unauthorised access to this Website or any of our sites or service and computer systems or networks connected to it, through hacking. You have the responsibilities to keep your login credentials to this Website confidential and not share with anyone. In case for whatever reason, the information on your login credentials to this Website gets leaked or compromised and used, Sapient or its directors, employees, agents, vendors, affiliates, associates, holding or subsidiary company(ies) shall not be held responsible, accountable or liable for any damage or loss to you consequent to such leakage and/or usage of the login credentials to this Website. Sapient may use certain technology on Website to collect information from visitors and may compile aggregate statistical information about how visitors use this Website, including information relating to the frequency of visits, the average length of visits, which pages are viewed during a visit. Sapient uses this information to improve its Website content and performance. No individually identifiable information is collected for this purpose and Sapient does not monitor individual visitor behaviour. All the information and contents on the Website is the exclusive property of Sapient and it is the sole owner of all the intellectual properties, rights, titles and interests."
									}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-oz92gm"}
							data-framer-name={
								"Details of Scheme level commission on Mutual funds are available with the Relationship Managers and would be produced on demand. This is on a best effort basis and rates are updated as and when actual rates are received from AMCs. We are a NISM certified / AMFI registered mutual fund distributor and not an RIA. We get compensated / incentivised by AMCs. We don't charge any fees for our services."
							}
							fonts={["FS;Satoshi-medium"]}
							layoutDependency={layoutDependency}
							layoutId={"VzPgAQo_g"}
							style={{
								"--extracted-r6o4lv": "rgb(51, 65, 85)",
								"--framer-paragraph-spacing": "0px",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									POugk4GoA: {
										children: (
											<React.Fragment>
												<motion.p
													dir={"auto"}
													style={{
														"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
														"--framer-font-family":
															'"Satoshi", "Satoshi Placeholder", sans-serif',
														"--framer-font-size": "12px",
														"--framer-font-weight": "500",
														"--framer-letter-spacing": "0.01em",
														"--framer-line-height": "150%",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(51, 65, 85))",
													}}
												>
													{
														"These Terms do not by whatsoever means provide any rights, interest, ownership or assign intellectual properties of the Website and its information and contents to you. You are not authorised to use, reproduce, download, copy, print and distribute any material on this Website whatsoever without Sapient\u2019s prior written approval. All the matters, information and contents supplied to you or received by you as confidential information shall be kept as such and not disclosed or divulged to anyone whatsoever. You undertake and agree that use of this Website is completely at your own risk. Sapient takes care to have the correct and accurate information and documents or data on this Website but does not provide guarantee or does not undertake and claim that the information is error free and you need to independently verify the information and data at your end before using or relying on it. Sapient or its directors, employees, agents, vendors, affiliates, associates, holding or subsidiary company(ies) shall not be held responsible, accountable or liable for any damage or loss to you consequent to your reliance and acting in any manner whatsoever on the basis of any information or data on this Website. You shall indemnify, defend and hold harmless Sapient, its directors, employees, affiliates, associates, holding or subsidiary company(ies) from any and all claims imposed on and losses incurred by or asserted on Sapient as a result of or related to your access and use of this Website, any non-compliance by user with the Terms hereof or any third party actions related to users receipt and use of the information, whether authorised or unauthorised. The Terms are exclusively based on and subject to Indian laws. You agree that any dispute as respect to the Terms of this Website shall be to the exclusive jurisdiction of the courts in Mumbai, Maharashtra, India."
													}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									dir={"auto"}
									style={{
										"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
										"--framer-font-family":
											'"Satoshi", "Satoshi Placeholder", sans-serif',
										"--framer-font-size": "20px",
										"--framer-font-weight": "500",
										"--framer-letter-spacing": "0.01em",
										"--framer-line-height": "150%",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(51, 65, 85))",
									}}
								>
									{
										"These Terms do not by whatsoever means provide any rights, interest, ownership or assign intellectual properties of the Website and its information and contents to you. You are not authorised to use, reproduce, download, copy, print and distribute any material on this Website whatsoever without Sapient\u2019s prior written approval. All the matters, information and contents supplied to you or received by you as confidential information shall be kept as such and not disclosed or divulged to anyone whatsoever. You undertake and agree that use of this Website is completely at your own risk. Sapient takes care to have the correct and accurate information and documents or data on this Website but does not provide guarantee or does not undertake and claim that the information is error free and you need to independently verify the information and data at your end before using or relying on it. Sapient or its directors, employees, agents, vendors, affiliates, associates, holding or subsidiary company(ies) shall not be held responsible, accountable or liable for any damage or loss to you consequent to your reliance and acting in any manner whatsoever on the basis of any information or data on this Website. You shall indemnify, defend and hold harmless Sapient, its directors, employees, affiliates, associates, holding or subsidiary company(ies) from any and all claims imposed on and losses incurred by or asserted on Sapient as a result of or related to your access and use of this Website, any non-compliance by user with the Terms hereof or any third party actions related to users receipt and use of the information, whether authorised or unauthorised. The Terms are exclusively based on and subject to Indian laws. You agree that any dispute as respect to the Terms of this Website shall be to the exclusive jurisdiction of the courts in Mumbai, Maharashtra, India."
									}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-nEI1x.framer-18xkvc5, .framer-nEI1x .framer-18xkvc5 { display: block; }",
	".framer-nEI1x.framer-ee8z4a { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1200px; }",
	".framer-nEI1x .framer-tp6i2a { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; max-width: 1200px; overflow: visible; padding: 0px; position: relative; width: 1200px; }",
	".framer-nEI1x .framer-jiwtt7 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 929px; word-break: break-word; word-wrap: break-word; }",
	".framer-nEI1x .framer-1yuu26p { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 757px; word-break: break-word; word-wrap: break-word; }",
	".framer-nEI1x .framer-3z5pam, .framer-nEI1x .framer-zyfkv9, .framer-nEI1x .framer-v6vijo, .framer-nEI1x .framer-oz92gm { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 1200px; word-break: break-word; word-wrap: break-word; }",
	".framer-nEI1x.framer-v-jtj1gt.framer-ee8z4a { padding: 0px 24px 0px 24px; }",
	".framer-nEI1x.framer-v-jtj1gt .framer-tp6i2a, .framer-nEI1x.framer-v-jtj1gt .framer-3z5pam, .framer-nEI1x.framer-v-jtj1gt .framer-zyfkv9, .framer-nEI1x.framer-v-jtj1gt .framer-v6vijo, .framer-nEI1x.framer-v-jtj1gt .framer-oz92gm, .framer-nEI1x.framer-v-1k0kr8x .framer-tp6i2a, .framer-nEI1x.framer-v-1k0kr8x .framer-3z5pam, .framer-nEI1x.framer-v-1k0kr8x .framer-zyfkv9, .framer-nEI1x.framer-v-1k0kr8x .framer-v6vijo, .framer-nEI1x.framer-v-1k0kr8x .framer-oz92gm, .framer-nEI1x.framer-v-1vh6bxh .framer-tp6i2a, .framer-nEI1x.framer-v-1vh6bxh .framer-jiwtt7, .framer-nEI1x.framer-v-1vh6bxh .framer-1yuu26p, .framer-nEI1x.framer-v-1vh6bxh .framer-3z5pam, .framer-nEI1x.framer-v-1vh6bxh .framer-zyfkv9, .framer-nEI1x.framer-v-1vh6bxh .framer-v6vijo, .framer-nEI1x.framer-v-1vh6bxh .framer-oz92gm { width: 100%; }",
	".framer-nEI1x.framer-v-1k0kr8x.framer-ee8z4a { padding: 0px 24px 0px 24px; width: 810px; }",
	".framer-nEI1x.framer-v-1vh6bxh.framer-ee8z4a { gap: 40px; padding: 0px 24px 0px 24px; width: 390px; }",
];
var FramerCqaHt9LUU = withCSS(Component, css, "framer-nEI1x");
var stdin_default = FramerCqaHt9LUU;
FramerCqaHt9LUU.displayName = "TermsConditions";
FramerCqaHt9LUU.defaultProps = {
	height: 1567,
	width: 1200,
};
addPropertyControls(FramerCqaHt9LUU, {
	variant: {
		options: ["zmbniIlTF", "KSAhnboJQ", "D7mfxnUc5", "POugk4GoA"],
		optionTitles: ["Desktop", "Desktop-sm", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerCqaHt9LUU,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Plus Jakarta Sans",
					source: "google",
					style: "normal",
					uiFamilyName: "Plus Jakarta Sans",
					url: "/fonts/LDIbaomQNQcsA88c7O9yZ4KMCoOg4IA6-91aHEjcWuA_TknNTxXUEKi4Rw.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Satoshi",
					source: "fontshare",
					style: "normal",
					uiFamilyName: "Satoshi",
					url: "/fonts/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2",
					weight: "500",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:terms-conditions
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "POugk4GoA",
	md: "D7mfxnUc5",
	xl: "KSAhnboJQ",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"af460206e137e8d824a96fddb1ea9788b0ffdc50cd99b3f451f16d44c1636491"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TermsConditionsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"af460206e137e8d824a96fddb1ea9788b0ffdc50cd99b3f451f16d44c1636491"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var terms_conditions_default = ComponentWithRoot;
export { terms_conditions_default as default };
